/* ============================================================================
   TICKET: Atendimentos 663 finalizados por engano (12-13/07/2026)
   Reabrindo para usuário 40005163 - análise FIES/débito de cooperação
   ============================================================================ */

-- Filtro básico: tipo 663, finalizados em 12-13 de julho
SELECT *
FROM HATENDIMENTOBASE WITH (NOLOCK)
WHERE CODCOLIGADA = 1
  AND CODTIPOATENDIMENTO = 663
  AND CAST(FECHAMENTO AS DATE) IN ('2026-07-12', '2026-07-13');


-- Se precisar mais dados (aluno, curso, etc), adicionar JOINs conforme necessário:
/*
SELECT 
    HATENDIMENTOBASE.CODATENDIMENTO,
    HATENDIMENTOBASE.FECHAMENTO,
    SATENDIMENTO.RA,
    SCURSO.NOME AS CURSO,
    STIPOCURSO.NOME AS POLO,
    PPESSOA.NOME
FROM HATENDIMENTOBASE WITH (NOLOCK)
    JOIN SATENDIMENTO WITH (NOLOCK) ON SATENDIMENTO.CODATENDIMENTO = HATENDIMENTOBASE.CODATENDIMENTO
    JOIN SALUNO WITH (NOLOCK) ON SALUNO.RA = SATENDIMENTO.RA
    JOIN SHABILITACAOFILIAL WITH (NOLOCK) ON SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SATENDIMENTO.IDHABILITACAOFILIAL
    JOIN SCURSO WITH (NOLOCK) ON SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
    JOIN STIPOCURSO WITH (NOLOCK) ON STIPOCURSO.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
    JOIN PPESSOA WITH (NOLOCK) ON PPESSOA.CODIGO = SALUNO.CODPESSOA
WHERE HATENDIMENTOBASE.CODCOLIGADA = 1
  AND HATENDIMENTOBASE.CODTIPOATENDIMENTO = 663
  AND CAST(HATENDIMENTOBASE.FECHAMENTO AS DATE) IN ('2026-07-12', '2026-07-13');
*/
