/* Log de movimentações de folgas com saldo acumulado.
   SALDO_ACUMULADO → saldo unificado de todas as categorias (um único banco de dias).
   Parâmetro: :CHAPA (ex.: '04788') */
/* Log de movimentações de folgas com saldo acumulado (banco único de dias).
   Parâmetro: :CHAPA (ex.: '04788') */
WITH MOVIMENTOS AS (
    SELECT
        ZMDFOLGAS.IDFOLGAS,
        ZMDFOLGAS.CODCOLIGADA,
        ZMDFOLGAS.CHAPA,
        PFUNC.NOME                                              AS NOMECOL,
        ZMDFOLGAS.DATASERVICO,
        ZMDFOLGAS.QTD,
        ZMDFOLGAS.CREDITODEBITO,
        CASE WHEN ZMDFOLGAS.CREDITODEBITO = 'C'
             THEN  ZMDFOLGAS.QTD
             ELSE -ZMDFOLGAS.QTD
        END                                                     AS MOVIMENTO
    FROM ZMDFOLGAS WITH (NOLOCK)
    JOIN PFUNC WITH (NOLOCK)
        ON PFUNC.CODCOLIGADA = ZMDFOLGAS.CODCOLIGADA
       AND PFUNC.CHAPA       = ZMDFOLGAS.CHAPA
    WHERE ZMDFOLGAS.CODCOLIGADA = 1
      AND ZMDFOLGAS.CHAPA       = :CHAPA
)
SELECT
    MOVIMENTOS.NOMECOL,
    MOVIMENTOS.DATASERVICO,
    MOVIMENTOS.QTD,
    MOVIMENTOS.CREDITODEBITO,
    SUM(MOVIMENTOS.MOVIMENTO) OVER (
        PARTITION BY MOVIMENTOS.CODCOLIGADA,
                     MOVIMENTOS.CHAPA
        ORDER BY     MOVIMENTOS.DATASERVICO,
                     MOVIMENTOS.IDFOLGAS
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    )                                                           AS SALDO_ACUMULADO,
    CASE
        WHEN SUM(MOVIMENTOS.MOVIMENTO) OVER (
             PARTITION BY MOVIMENTOS.CODCOLIGADA,
                          MOVIMENTOS.CHAPA
             ORDER BY     MOVIMENTOS.DATASERVICO,
                          MOVIMENTOS.IDFOLGAS
             ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) < 0 THEN 'SALDO NEGATIVO'
    END                                                         AS ALERTA
FROM MOVIMENTOS
ORDER BY MOVIMENTOS.DATASERVICO,
         MOVIMENTOS.IDFOLGAS;

-- ============================================================

-- Retorna 1 RA por polo presencial (IES), considerando aluno ATIVO e
-- matrícula no período com status MATRICULADO (PERIODO LETIVO).
-- Se um polo não tiver aluno elegível, ainda assim aparece com RA nulo.
-- Parâmetros esperados: :CODPERLET (ex.: 2026.1)
WITH POLOS AS (
       SELECT
              STIPOCURSO.CODTIPOCURSO,
              STIPOCURSO.NOME AS IES
       FROM STIPOCURSO WITH (NOLOCK)
       WHERE STIPOCURSO.CODCOLIGADA = 1
         AND STIPOCURSO.CODTIPOCURSO IN (1, 195, 196, 281, 285, 345, 357, 424)
), BASE AS (
       SELECT
              SHABILITACAOFILIAL.CODTIPOCURSO,
              SALUNO.RA,
              PPESSOA.NOME AS NOMEALUNO,
              SPLETIVO.CODPERLET,
              ROW_NUMBER() OVER (
                     PARTITION BY SHABILITACAOFILIAL.CODTIPOCURSO
                     ORDER BY NEWID()  -- ← Aleatório
              ) AS RN
       FROM SHABILITACAOALUNO WITH (NOLOCK)
       JOIN SALUNO WITH (NOLOCK)
              ON SALUNO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
          AND SALUNO.RA = SHABILITACAOALUNO.RA
       JOIN PPESSOA WITH (NOLOCK)
              ON PPESSOA.CODIGO = SALUNO.CODPESSOA
       JOIN SHABILITACAOFILIAL WITH (NOLOCK)
              ON SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
          AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
       JOIN SMATRICPL WITH (NOLOCK)
              ON SMATRICPL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
          AND SMATRICPL.RA = SHABILITACAOALUNO.RA
          AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
       JOIN SPLETIVO WITH (NOLOCK)
              ON SPLETIVO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
          AND SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
       WHERE SHABILITACAOALUNO.CODCOLIGADA = 1
         AND LTRIM(RTRIM(SPLETIVO.CODPERLET)) = LTRIM(RTRIM(CONCAT('', :CODPERLET)))
         AND SHABILITACAOFILIAL.CODTIPOCURSO IN (1, 195, 196, 281, 285, 345, 357, 424)
         AND EXISTS (
                SELECT TOP 1 1
                FROM SSTATUS WITH (NOLOCK)
                WHERE SSTATUS.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
                  AND SSTATUS.CODSTATUS = SHABILITACAOALUNO.CODSTATUS
                  AND SSTATUS.DESCRICAO = 'ATIVO'
         )
         AND EXISTS (
                SELECT TOP 1 1
                FROM SSTATUS WITH (NOLOCK)
                WHERE SSTATUS.CODCOLIGADA = SMATRICPL.CODCOLIGADA
                  AND SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS
                  AND SSTATUS.DESCRICAO = 'MATRICULADO (PERIODO LETIVO)'
         )
)
SELECT
       POLOS.CODTIPOCURSO,
       POLOS.IES,
       BASE.RA,
       BASE.NOMEALUNO,
       BASE.CODPERLET
FROM POLOS
LEFT JOIN BASE
       ON BASE.CODTIPOCURSO = POLOS.CODTIPOCURSO
      AND BASE.RN = 1
ORDER BY POLOS.CODTIPOCURSO;
