
/* ============================================================================
   REPOSITÓRIO DE CONSULTAS SQL — TOTVS RM / UNINTA
   ============================================================================
   Última atualização: 13/03/2026

   ÍNDICE:
     1. LOOKUPS RÁPIDOS .............. Exploração de tabelas e relacionamentos
     2. ALUNOS ....................... Dados cadastrais e acadêmicos de alunos
     3. MATRÍCULAS E PERÍODOS ........ Situação de matrícula por período letivo
     4. EMAIL INSTITUCIONAL .......... Geração de sugestão de e-mail @discentes
     5. PESSOAS E USUÁRIOS ........... Dados de pessoas e usuários do sistema
     6. PROFESSORES .................. Polos e disciplinas dos professores
     7. ATENDIMENTOS ................. Solicitações e atendimentos acadêmicos
     8. DESEMPENHO ACADÊMICO ......... Aprovação e reprovação por disciplina
     9. LISTAS AUXILIARES ............ Listas de valores para uso em relatórios
    10. FORMULÁRIOS E VALIDAÇÕES ..... Validações para formulários do portal
    11. BIBLIOTECA ................... Empréstimos, multas e acervo bibliográfico
    12. AUDITORIA .................... Histórico de alterações via TOTVSAUDIT
   ============================================================================ */


/* ============================================================================
   1. LOOKUPS RÁPIDOS
   ============================================================================ */

-- Exibe as tabelas filhas (relacionamentos) vinculadas à tabela GUSRPERFIL
SELECT * FROM GLINKSREL WITH (NOLOCK) WHERE MASTERTABLE = 'GUSRPERFIL';

-- Exibe os relacionamentos vinculados à tabela SCURSO (curso)
SELECT * FROM GLINKSREL WITH (NOLOCK) WHERE MASTERTABLE = 'SCURSO';

-- Exibe os relacionamentos vinculados à tabela SSTATUS (status)
SELECT * FROM GLINKSREL WITH (NOLOCK) WHERE MASTERTABLE = 'SSTATUS';

-- Exibe o relacionamento direto de SALUNO para SHABILITACAOALUNO
SELECT * FROM GLINKSREL WITH (NOLOCK) WHERE MASTERTABLE = 'SALUNO' AND CHILDTABLE = 'SHABILITACAOALUNO';

-- Lista todas as turmas vinculadas a um professor específico pelo código do professor
SELECT * FROM SPROFESSORTURMA WITH (NOLOCK) WHERE CODPROF = '1-03682';

-- Retorna os dados de um usuário específico pelo código de usuário
SELECT * FROM GUSUARIO WITH (NOLOCK) WHERE CODUSUARIO = '1-07337';

-- Lista todos os códigos de pessoa cadastrados no sistema
SELECT CODIGO FROM PPESSOA WITH (NOLOCK);

-- Busca uma pessoa pelo endereço de e-mail cadastrado
SELECT * FROM PPESSOA WITH (NOLOCK) WHERE EMAIL = 'JOAQUIMISMAELDESOUSATEIXEIRA@GMAIL.COM';


/* ============================================================================
   2. ALUNOS
   ============================================================================ */

-- Retorna o nome completo, primeiro nome, RA e nome social de alunos de
-- cursos de graduação (CODTIPOCURSO = 1) da coligada 1
SELECT
    PPESSOA.NOME,
    SUBSTRING(PPESSOA.NOME, 1, CHARINDEX(' ', PPESSOA.NOME + ' ') - 1) AS [PRIMEIRO NOME],
    SALUNO.RA,
    PPESSOA.NOMESOCIAL
FROM SALUNO WITH (NOLOCK)
    JOIN PPESSOA WITH (NOLOCK)
        ON PPESSOA.CODIGO = SALUNO.CODPESSOA
    JOIN SHABILITACAOALUNO WITH (NOLOCK)
        ON SHABILITACAOALUNO.CODCOLIGADA = SALUNO.CODCOLIGADA
        AND SHABILITACAOALUNO.RA = SALUNO.RA
    JOIN SHABILITACAOFILIAL WITH (NOLOCK)
        ON SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
        AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
    JOIN SCURSO WITH (NOLOCK)
        ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
        AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
WHERE
    SHABILITACAOFILIAL.CODCOLIGADA = 1
    AND SCURSO.CODTIPOCURSO = 1;


-- Busca RA, nome e CPF de um aluno a partir de um CPF específico
SELECT
    SALUNO.RA,
    PPESSOA.NOME,
    PPESSOA.CPF
FROM PPESSOA WITH (NOLOCK)
JOIN SALUNO WITH (NOLOCK)
    ON SALUNO.CODPESSOA = PPESSOA.CODIGO
WHERE PPESSOA.CPF = '13334582744';


-- Busca RA, nome e status de alunos a partir de uma lista de CPFs.
-- Filtra apenas alunos ATIVOS ou GRADUADOS na coligada 1.
SELECT DISTINCT
    SALUNO.RA,
    PPESSOA.NOME,
    PPESSOA.CPF
FROM PPESSOA WITH (NOLOCK)
JOIN SALUNO WITH (NOLOCK)
    ON SALUNO.CODPESSOA = PPESSOA.CODIGO
JOIN SHABILITACAOALUNO WITH (NOLOCK)
    ON SHABILITACAOALUNO.CODCOLIGADA = SALUNO.CODCOLIGADA
   AND SHABILITACAOALUNO.RA = SALUNO.RA
JOIN SSTATUS WITH (NOLOCK)
    ON SSTATUS.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
   AND SSTATUS.CODSTATUS = SHABILITACAOALUNO.CODSTATUS
WHERE PPESSOA.CPF IN (
    '62335199340', '93113315387', '05895155359', '06999742324', '06846143327',
    '62403847399', '08251343313', '03428429354', '62541164300', '63164714327',
    '08645931397', '07457803343', '08117472392', '82237077304', '07513726337',
    '04930790336', '04434861310', '83324119391', '01031634339', '60844478300',
    '04685174305', '07830698392', '80368263304', '95119540325', '00441494331',
    '67899986320', '05368958307', '02824726300', '09020374397', '03198507308',
    '00740570307', '15644946754', '07039176335', '87256932391', '04655175362',
    '00372219306', '00702570354', '62548346340', '03695060492', '62453099302',
    '87787539372', '03832846352', '05240967326', '97910341334', '01796532371',
    '89557662387', '08371739303', '08374726369'
)
AND SALUNO.CODCOLIGADA = 1
AND SSTATUS.DESCRICAO IN ('ATIVO', 'GRADUADO(A)');


-- Dados completos do aluno: polo (com indicador de permissão), curso com código INEP,
-- turno, modalidade, tipo de ingresso, situação na habilitação e no período letivo.
-- Usa parâmetros :$CODCOLIGADA e :RA (compatível com relatórios TOTVS RM).
SELECT
    CONCAT(SALUNO.RA, ' - ', PPESSOA.NOME, ' (', PPESSOA.CPF, ')') AS [ALUNO(A)],
    SPLETIVO.IDPERLET,
    CONCAT(
        STIPOCURSO.CODTIPOCURSO, ' - ',
        STIPOCURSO.NOME,
        (CASE WHEN ZMDPOLOS.CODINEP IS NOT NULL THEN CONCAT(' (', ZMDPOLOS.CODINEP, ')') END),
        (CASE
            WHEN NOT EXISTS (
                SELECT 1
                FROM SUSUARIOFILIAL WITH (NOLOCK)
                WHERE SUSUARIOFILIAL.CODCOLIGADA  = SHABILITACAOFILIAL.CODCOLIGADA
                  AND SUSUARIOFILIAL.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
                  AND SUSUARIOFILIAL.CODFILIAL    = SHABILITACAOFILIAL.CODFILIAL
                  AND SUSUARIOFILIAL.CODUSUARIO   = PPESSOA.CODUSUARIO
            ) THEN ' SEM PERMISSÃO'
        END)
    ) AS POLO,
    CONCAT(
        SCURSO.NOME, ' (',
        (SELECT TOP 1 CODCURINEP
         FROM SCURSO A WITH (NOLOCK)
         WHERE A.CODCOLIGADA = SCURSO.CODCOLIGADA
           AND A.CODCURINEP IS NOT NULL
           AND (
               (STIPOCURSO.NOME LIKE 'POLO %SEMI%'        AND (A.COMPLEMENTO = SCURSO.COMPLEMENTO AND A.CODTIPOCURSO = 323))
               OR (STIPOCURSO.NOME LIKE 'POLO %' AND STIPOCURSO.NOME NOT LIKE '%SEMI%' AND (A.COMPLEMENTO = SCURSO.COMPLEMENTO AND A.CODTIPOCURSO = 4))
               OR (STIPOCURSO.NOME NOT LIKE 'POLO %'      AND A.CODCURSO = SCURSO.CODCURSO)
           )),
        ')'
    ) AS CURSO,
    SPLETIVO.CODPERLET          AS PERIODOLETIVO,
    STATUSPL.DESCRICAO          AS STATUSPERIODO,
    SMATRICPL.PERIODO,
    SHABILITACAOALUNO.IDHABILITACAOFILIAL,
    SHABILITACAOALUNO.IDHABILITACAOFILIALORIGEM,
    STATUSHAB.DESCRICAO         AS STATUSHAB,
    STURNO.NOME                 AS TURNO,
    (CASE
        WHEN ZMDPOLOS.TIPOENSINO = 'P'                                    THEN 'Presencial'
        WHEN ZMDPOLOS.TIPOENSINO = 'E' AND ISNULL(ZMDPOLOS.POLODIGITAL, 'N') = 'N' THEN 'Flex'
        WHEN ZMDPOLOS.TIPOENSINO = 'E' AND ISNULL(ZMDPOLOS.POLODIGITAL, 'N') = 'S' THEN 'Digital'
        WHEN ZMDPOLOS.TIPOENSINO = 'S'                                    THEN 'Semipresencial'
    END)                        AS MODALIDADE,
    STIPOINGRESSO.DESCRICAO     AS TIPOINGRESSO,
    SHABILITACAOALUNO.DTINGRESSO
FROM SHABILITACAOALUNO WITH (NOLOCK)
    /* Forma de ingresso */
    LEFT JOIN STIPOINGRESSO WITH (NOLOCK)
           ON STIPOINGRESSO.CODCOLIGADA       = SHABILITACAOALUNO.CODCOLIGADA
          AND STIPOINGRESSO.CODTIPOINGRESSO   = SHABILITACAOALUNO.CODTIPOINGRESSO
    /* Status na habilitação */
    JOIN SSTATUS STATUSHAB WITH (NOLOCK)
      ON STATUSHAB.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
     AND STATUSHAB.CODSTATUS   = SHABILITACAOALUNO.CODSTATUS
    /* Aluno e pessoa */
    JOIN SALUNO WITH (NOLOCK)
         JOIN PPESSOA WITH (NOLOCK)
           ON PPESSOA.CODIGO = SALUNO.CODPESSOA
      ON SALUNO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
     AND SALUNO.RA          = SHABILITACAOALUNO.RA
    /* Curso */
    JOIN SHABILITACAOFILIAL WITH (NOLOCK)
         JOIN STURNO WITH (NOLOCK)
           ON STURNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
          AND STURNO.CODTURNO    = SHABILITACAOFILIAL.CODTURNO
         JOIN SCURSO WITH (NOLOCK)
           ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
          AND SCURSO.CODCURSO    = SHABILITACAOFILIAL.CODCURSO
      ON SHABILITACAOFILIAL.CODCOLIGADA         = SHABILITACAOALUNO.CODCOLIGADA
     AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL  = SHABILITACAOALUNO.IDHABILITACAOFILIAL
    /* Polo / nível de ensino */
    JOIN STIPOCURSO WITH (NOLOCK)
         LEFT JOIN ZMDPOLOS WITH (NOLOCK)
                ON ZMDPOLOS.CODCOLIGADA = STIPOCURSO.CODCOLIGADA
               AND ZMDPOLOS.CODPOLO     = STIPOCURSO.CODTIPOCURSO
      ON STIPOCURSO.CODCOLIGADA  = SHABILITACAOFILIAL.CODCOLIGADA
     AND STIPOCURSO.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
    /* Período letivo */
    LEFT JOIN SMATRICPL WITH (NOLOCK)
              JOIN SPLETIVO WITH (NOLOCK)
                ON SPLETIVO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
               AND SPLETIVO.IDPERLET    = SMATRICPL.IDPERLET
              JOIN SSTATUS STATUSPL WITH (NOLOCK)
                ON STATUSPL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
               AND STATUSPL.CODSTATUS   = SMATRICPL.CODSTATUS
      ON SMATRICPL.CODCOLIGADA          = SHABILITACAOALUNO.CODCOLIGADA
     AND SMATRICPL.IDHABILITACAOFILIAL  = SHABILITACAOALUNO.IDHABILITACAOFILIAL
     AND SMATRICPL.RA                   = SHABILITACAOALUNO.RA
WHERE SHABILITACAOALUNO.CODCOLIGADA = :$CODCOLIGADA
  AND SHABILITACAOALUNO.RA          = :RA;


-- Disciplinas do aluno no período letivo MAIS ATUAL (baseado no IDPERLET mais recente).
-- Inclui nota, falta, média de aprovação e percentual de frequência mínima.
-- Usa parâmetros :$CODCOLIGADA e :RA.
SELECT
    CONCAT(SALUNO.RA, ' - ', PPESSOA.NOME, ' (', PPESSOA.CPF, ')') AS [ALUNO(A)],
    SPLETIVO.IDPERLET,
    SPLETIVO.CODPERLET          AS PERIODOLETIVO,
    CONCAT(
        STIPOCURSO.CODTIPOCURSO, ' - ',
        STIPOCURSO.NOME,
        (CASE WHEN ZMDPOLOS.CODINEP IS NOT NULL THEN CONCAT(' (', ZMDPOLOS.CODINEP, ')') END),
        (CASE
            WHEN NOT EXISTS (
                SELECT 1
                FROM SUSUARIOFILIAL WITH (NOLOCK)
                WHERE SUSUARIOFILIAL.CODCOLIGADA  = SHABILITACAOFILIAL.CODCOLIGADA
                  AND SUSUARIOFILIAL.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
                  AND SUSUARIOFILIAL.CODFILIAL    = SHABILITACAOFILIAL.CODFILIAL
                  AND SUSUARIOFILIAL.CODUSUARIO   = PPESSOA.CODUSUARIO
            ) THEN ' SEM PERMISSÃO'
        END)
    ) AS POLO,
    CONCAT(
        SCURSO.NOME, ' (',
        (SELECT TOP 1 CODCURINEP
         FROM SCURSO A WITH (NOLOCK)
         WHERE A.CODCOLIGADA = SCURSO.CODCOLIGADA
           AND A.CODCURINEP IS NOT NULL
           AND (
               (STIPOCURSO.NOME LIKE 'POLO %SEMI%'        AND (A.COMPLEMENTO = SCURSO.COMPLEMENTO AND A.CODTIPOCURSO = 323))
               OR (STIPOCURSO.NOME LIKE 'POLO %' AND STIPOCURSO.NOME NOT LIKE '%SEMI%' AND (A.COMPLEMENTO = SCURSO.COMPLEMENTO AND A.CODTIPOCURSO = 4))
               OR (STIPOCURSO.NOME NOT LIKE 'POLO %'      AND A.CODCURSO = SCURSO.CODCURSO)
           )),
        ')'
    ) AS CURSO,
    STATUSPL.DESCRICAO          AS STATUSPERIODO,
    SMATRICPL.PERIODO,
    SHABILITACAOALUNO.IDHABILITACAOFILIAL,
    SHABILITACAOALUNO.IDHABILITACAOFILIALORIGEM,
    STATUSHAB.DESCRICAO         AS STATUSHAB,
    STURNO.NOME                 AS TURNO,
    (CASE
        WHEN ZMDPOLOS.TIPOENSINO = 'P'                                    THEN 'Presencial'
        WHEN ZMDPOLOS.TIPOENSINO = 'E' AND ISNULL(ZMDPOLOS.POLODIGITAL, 'N') = 'N' THEN 'Flex'
        WHEN ZMDPOLOS.TIPOENSINO = 'E' AND ISNULL(ZMDPOLOS.POLODIGITAL, 'N') = 'S' THEN 'Digital'
        WHEN ZMDPOLOS.TIPOENSINO = 'S'                                    THEN 'Semipresencial'
    END)                        AS MODALIDADE,
    STIPOINGRESSO.DESCRICAO     AS TIPOINGRESSO,
    SHABILITACAOALUNO.DTINGRESSO,
    /* Informações da disciplina */
    SDISCIPLINA.CODDISC,
    SDISCIPLINA.NOME            AS DISCIPLINA,
    SMATRICULA.IDTURMADISC,
    STURMADISC.CODTURMA,
    SMATRICULA.CODSTATUS        AS CODSTATUSDISC,
    STATUSDISC.DESCRICAO        AS STATUSDISCIPLINA
FROM SHABILITACAOALUNO WITH (NOLOCK)
    LEFT JOIN STIPOINGRESSO WITH (NOLOCK)
           ON STIPOINGRESSO.CODCOLIGADA     = SHABILITACAOALUNO.CODCOLIGADA
          AND STIPOINGRESSO.CODTIPOINGRESSO = SHABILITACAOALUNO.CODTIPOINGRESSO
    JOIN SSTATUS STATUSHAB WITH (NOLOCK)
      ON STATUSHAB.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
     AND STATUSHAB.CODSTATUS   = SHABILITACAOALUNO.CODSTATUS
    JOIN SALUNO WITH (NOLOCK)
         JOIN PPESSOA WITH (NOLOCK)
           ON PPESSOA.CODIGO = SALUNO.CODPESSOA
      ON SALUNO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
     AND SALUNO.RA          = SHABILITACAOALUNO.RA
    JOIN SHABILITACAOFILIAL WITH (NOLOCK)
         JOIN STURNO WITH (NOLOCK)
           ON STURNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
          AND STURNO.CODTURNO    = SHABILITACAOFILIAL.CODTURNO
         JOIN SCURSO WITH (NOLOCK)
           ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
          AND SCURSO.CODCURSO    = SHABILITACAOFILIAL.CODCURSO
      ON SHABILITACAOFILIAL.CODCOLIGADA        = SHABILITACAOALUNO.CODCOLIGADA
     AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
    JOIN STIPOCURSO WITH (NOLOCK)
         LEFT JOIN ZMDPOLOS WITH (NOLOCK)
                ON ZMDPOLOS.CODCOLIGADA = STIPOCURSO.CODCOLIGADA
               AND ZMDPOLOS.CODPOLO     = STIPOCURSO.CODTIPOCURSO
      ON STIPOCURSO.CODCOLIGADA  = SHABILITACAOFILIAL.CODCOLIGADA
     AND STIPOCURSO.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
    /* Filtra apenas o período letivo mais atual do aluno */
    JOIN SMATRICPL WITH (NOLOCK)
         JOIN SPLETIVO WITH (NOLOCK)
           ON SPLETIVO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
          AND SPLETIVO.IDPERLET    = SMATRICPL.IDPERLET
         JOIN SSTATUS STATUSPL WITH (NOLOCK)
           ON STATUSPL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
          AND STATUSPL.CODSTATUS   = SMATRICPL.CODSTATUS
      ON SMATRICPL.CODCOLIGADA         = SHABILITACAOALUNO.CODCOLIGADA
     AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
     AND SMATRICPL.RA                  = SHABILITACAOALUNO.RA
     AND SMATRICPL.IDPERLET = (
         SELECT TOP 1 IDPERLET
         FROM SMATRICPL MP WITH (NOLOCK)
         WHERE MP.CODCOLIGADA         = SHABILITACAOALUNO.CODCOLIGADA
           AND MP.RA                  = SHABILITACAOALUNO.RA
           AND MP.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
         ORDER BY MP.IDPERLET DESC
     )
    /* Matrículas em disciplinas */
    JOIN SMATRICULA WITH (NOLOCK)
         JOIN STURMADISC WITH (NOLOCK)
              JOIN SDISCIPLINA WITH (NOLOCK)
                ON SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
               AND SDISCIPLINA.CODDISC     = STURMADISC.CODDISC
           ON STURMADISC.CODCOLIGADA  = SMATRICULA.CODCOLIGADA
          AND STURMADISC.IDTURMADISC  = SMATRICULA.IDTURMADISC
         JOIN SSTATUS STATUSDISC WITH (NOLOCK)
           ON STATUSDISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
          AND STATUSDISC.CODSTATUS   = SMATRICULA.CODSTATUS
      ON SMATRICULA.CODCOLIGADA         = SMATRICPL.CODCOLIGADA
     AND SMATRICULA.IDPERLET            = SMATRICPL.IDPERLET
     AND SMATRICULA.RA                  = SMATRICPL.RA
     AND SMATRICULA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
WHERE SHABILITACAOALUNO.CODCOLIGADA = :$CODCOLIGADA
  AND SHABILITACAOALUNO.RA          = :RA
ORDER BY SDISCIPLINA.NOME;


-- Disciplinas do aluno em TODOS os períodos letivos (via tabela SMATRICULA).
-- Retorna disciplina, turma e status de cada matrícula em disciplina.
-- Usa parâmetros :$CODCOLIGADA e :RA.
SELECT
    CONCAT(SALUNO.RA, ' - ', PPESSOA.NOME, ' (', PPESSOA.CPF, ')') AS [ALUNO(A)],
    SPLETIVO.IDPERLET,
    CONCAT(
        STIPOCURSO.CODTIPOCURSO, ' - ',
        STIPOCURSO.NOME,
        (CASE WHEN ZMDPOLOS.CODINEP IS NOT NULL THEN CONCAT(' (', ZMDPOLOS.CODINEP, ')') END),
        (CASE
            WHEN NOT EXISTS (
                SELECT 1
                FROM SUSUARIOFILIAL WITH (NOLOCK)
                WHERE SUSUARIOFILIAL.CODCOLIGADA  = SHABILITACAOFILIAL.CODCOLIGADA
                  AND SUSUARIOFILIAL.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
                  AND SUSUARIOFILIAL.CODFILIAL    = SHABILITACAOFILIAL.CODFILIAL
                  AND SUSUARIOFILIAL.CODUSUARIO   = PPESSOA.CODUSUARIO
            ) THEN ' SEM PERMISSÃO'
        END)
    ) AS POLO,
    CONCAT(
        SCURSO.NOME, ' (',
        (SELECT TOP 1 CODCURINEP
         FROM SCURSO A WITH (NOLOCK)
         WHERE A.CODCOLIGADA = SCURSO.CODCOLIGADA
           AND A.CODCURINEP IS NOT NULL
           AND (
               (STIPOCURSO.NOME LIKE 'POLO %SEMI%'        AND (A.COMPLEMENTO = SCURSO.COMPLEMENTO AND A.CODTIPOCURSO = 323))
               OR (STIPOCURSO.NOME LIKE 'POLO %' AND STIPOCURSO.NOME NOT LIKE '%SEMI%' AND (A.COMPLEMENTO = SCURSO.COMPLEMENTO AND A.CODTIPOCURSO = 4))
               OR (STIPOCURSO.NOME NOT LIKE 'POLO %'      AND A.CODCURSO = SCURSO.CODCURSO)
           )),
        ')'
    ) AS CURSO,
    SPLETIVO.CODPERLET          AS PERIODOLETIVO,
    STATUSPL.DESCRICAO          AS STATUSPERIODO,
    SMATRICPL.PERIODO,
    SHABILITACAOALUNO.IDHABILITACAOFILIAL,
    SHABILITACAOALUNO.IDHABILITACAOFILIALORIGEM,
    STATUSHAB.DESCRICAO         AS STATUSHAB,
    STURNO.NOME                 AS TURNO,
    (CASE
        WHEN ZMDPOLOS.TIPOENSINO = 'P'                                    THEN 'Presencial'
        WHEN ZMDPOLOS.TIPOENSINO = 'E' AND ISNULL(ZMDPOLOS.POLODIGITAL, 'N') = 'N' THEN 'Flex'
        WHEN ZMDPOLOS.TIPOENSINO = 'E' AND ISNULL(ZMDPOLOS.POLODIGITAL, 'N') = 'S' THEN 'Digital'
        WHEN ZMDPOLOS.TIPOENSINO = 'S'                                    THEN 'Semipresencial'
    END)                        AS MODALIDADE,
    STIPOINGRESSO.DESCRICAO     AS TIPOINGRESSO,
    SHABILITACAOALUNO.DTINGRESSO,
    STATUSDISC.DESCRICAO        AS STATUSDISCIPLINA,
    SDISCIPLINA.NOME            AS DISCIPLINA,
    STURMADISC.CODTURMA         AS TURMADISCIPLINA
FROM SHABILITACAOALUNO WITH (NOLOCK)
    LEFT JOIN STIPOINGRESSO WITH (NOLOCK)
           ON STIPOINGRESSO.CODCOLIGADA     = SHABILITACAOALUNO.CODCOLIGADA
          AND STIPOINGRESSO.CODTIPOINGRESSO = SHABILITACAOALUNO.CODTIPOINGRESSO
    JOIN SSTATUS STATUSHAB WITH (NOLOCK)
      ON STATUSHAB.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
     AND STATUSHAB.CODSTATUS   = SHABILITACAOALUNO.CODSTATUS
    JOIN SALUNO WITH (NOLOCK)
         JOIN PPESSOA WITH (NOLOCK)
           ON PPESSOA.CODIGO = SALUNO.CODPESSOA
      ON SALUNO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
     AND SALUNO.RA          = SHABILITACAOALUNO.RA
    JOIN SHABILITACAOFILIAL WITH (NOLOCK)
         JOIN STURNO WITH (NOLOCK)
           ON STURNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
          AND STURNO.CODTURNO    = SHABILITACAOFILIAL.CODTURNO
         JOIN SCURSO WITH (NOLOCK)
           ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
          AND SCURSO.CODCURSO    = SHABILITACAOFILIAL.CODCURSO
      ON SHABILITACAOFILIAL.CODCOLIGADA        = SHABILITACAOALUNO.CODCOLIGADA
     AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
    JOIN STIPOCURSO WITH (NOLOCK)
         LEFT JOIN ZMDPOLOS WITH (NOLOCK)
                ON ZMDPOLOS.CODCOLIGADA = STIPOCURSO.CODCOLIGADA
               AND ZMDPOLOS.CODPOLO     = STIPOCURSO.CODTIPOCURSO
      ON STIPOCURSO.CODCOLIGADA  = SHABILITACAOFILIAL.CODCOLIGADA
     AND STIPOCURSO.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
    LEFT JOIN SMATRICPL WITH (NOLOCK)
              JOIN SPLETIVO WITH (NOLOCK)
                ON SPLETIVO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
               AND SPLETIVO.IDPERLET    = SMATRICPL.IDPERLET
              JOIN SSTATUS STATUSPL WITH (NOLOCK)
                ON STATUSPL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
               AND STATUSPL.CODSTATUS   = SMATRICPL.CODSTATUS
      ON SMATRICPL.CODCOLIGADA         = SHABILITACAOALUNO.CODCOLIGADA
     AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
     AND SMATRICPL.RA                  = SHABILITACAOALUNO.RA
    JOIN SMATRICULA WITH (NOLOCK)
      ON SMATRICULA.CODCOLIGADA        = SALUNO.CODCOLIGADA
     AND SMATRICULA.RA                 = SALUNO.RA
     AND SMATRICULA.IDPERLET           = SMATRICPL.IDPERLET
     AND SMATRICULA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
    JOIN STURMADISC WITH (NOLOCK)
      ON STURMADISC.CODCOLIGADA  = SMATRICULA.CODCOLIGADA
     AND STURMADISC.IDTURMADISC  = SMATRICULA.IDTURMADISC
    JOIN SDISCIPLINA WITH (NOLOCK)
      ON SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
     AND SDISCIPLINA.CODDISC     = STURMADISC.CODDISC
    JOIN SSTATUS STATUSDISC WITH (NOLOCK)
      ON STATUSDISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
     AND STATUSDISC.CODSTATUS   = SMATRICULA.CODSTATUS
WHERE SHABILITACAOALUNO.CODCOLIGADA = :$CODCOLIGADA
  AND SHABILITACAOALUNO.RA          = :RA;


/* ============================================================================
   3. MATRÍCULAS E PERÍODOS LETIVOS
   ============================================================================ */

-- Lista alunos matriculados, pendentes ou trancados em um período letivo específico
-- para cursos presenciais/semipresenciais (filtro por CODTIPOCURSO).
-- Inclui nome, CPF, curso, turno e tipo de matrícula.
SELECT DISTINCT
    SMATRICPL.CODCOLIGADA,
    SMATRICPL.RA,
    SMATRICPL.IDHABILITACAOFILIAL,
    SPLETIVO.CODPERLET,
    SCURSO.CODCURSO,
    SCURSO.NOME              AS NOMECURSO,
    STURNO.NOME              AS NOMETURNO,
    PPESSOA.NOME             AS NOMEALUNO,
    PPESSOA.CPF,
    SSTATUS.DESCRICAO        AS NOMESTATUS,
    STIPOMATRICULA.DESCRICAO AS NOMETIPOMAT
FROM SHABILITACAOALUNO WITH (NOLOCK)
    JOIN SHABILITACAOFILIAL WITH (NOLOCK)
      ON SHABILITACAOALUNO.CODCOLIGADA         = SHABILITACAOFILIAL.CODCOLIGADA
     AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
    JOIN SPLETIVO WITH (NOLOCK)
      ON SPLETIVO.CODCOLIGADA   = SHABILITACAOFILIAL.CODCOLIGADA
     AND SPLETIVO.CODTIPOCURSO  = SHABILITACAOFILIAL.CODTIPOCURSO
    JOIN SMATRICPL WITH (NOLOCK)
      ON SMATRICPL.CODCOLIGADA         = SHABILITACAOALUNO.CODCOLIGADA
     AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
     AND SMATRICPL.RA                  = SHABILITACAOALUNO.RA
     AND SMATRICPL.IDPERLET            = SPLETIVO.IDPERLET
    JOIN SCURSO WITH (NOLOCK)
      ON SHABILITACAOFILIAL.CODCOLIGADA = SCURSO.CODCOLIGADA
     AND SHABILITACAOFILIAL.CODCURSO    = SCURSO.CODCURSO
    JOIN SHABILITACAO WITH (NOLOCK)
      ON SHABILITACAO.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
     AND SCURSO.CODCOLIGADA         = SHABILITACAO.CODCOLIGADA
     AND SCURSO.CODCURSO            = SHABILITACAO.CODCURSO
    JOIN SGRADE WITH (NOLOCK)
      ON SGRADE.CODCOLIGADA     = SHABILITACAOFILIAL.CODCOLIGADA
     AND SGRADE.CODCURSO        = SHABILITACAOFILIAL.CODCURSO
     AND SGRADE.CODHABILITACAO  = SHABILITACAOFILIAL.CODHABILITACAO
     AND SGRADE.CODGRADE        = SHABILITACAOFILIAL.CODGRADE
    JOIN STURNO WITH (NOLOCK)
      ON SHABILITACAOFILIAL.CODCOLIGADA = STURNO.CODCOLIGADA
     AND SHABILITACAOFILIAL.CODTURNO    = STURNO.CODTURNO
    JOIN SSTATUS WITH (NOLOCK)
      ON SSTATUS.CODCOLIGADA = SMATRICPL.CODCOLIGADA
     AND SSTATUS.CODSTATUS   = SMATRICPL.CODSTATUS
    JOIN SALUNO WITH (NOLOCK)
      ON SALUNO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
     AND SALUNO.RA          = SMATRICPL.RA
    JOIN PPESSOA WITH (NOLOCK)
      ON PPESSOA.CODIGO = SALUNO.CODPESSOA
    LEFT JOIN SSTATUS SSTATUSRES WITH (NOLOCK)
      ON SMATRICPL.CODCOLIGADA  = SSTATUSRES.CODCOLIGADA
     AND SMATRICPL.CODSTATUSRES = SSTATUSRES.CODSTATUS
    LEFT JOIN SMATRICPLITEMCNT WITH (NOLOCK)
      ON SMATRICPL.CODCOLIGADA         = SMATRICPLITEMCNT.CODCOLIGADA
     AND SMATRICPL.IDPERLET            = SMATRICPLITEMCNT.IDPERLET
     AND SMATRICPL.IDHABILITACAOFILIAL = SMATRICPLITEMCNT.IDHABILITACAOFILIAL
     AND SMATRICPL.RA                  = SMATRICPLITEMCNT.RA
    LEFT JOIN STIPOMATRICULA WITH (NOLOCK)
      ON SMATRICPL.CODCOLIGADA = STIPOMATRICULA.CODCOLIGADA
     AND SMATRICPL.CODTIPOMAT  = STIPOMATRICULA.CODTIPOMAT
WHERE SMATRICPL.CODCOLIGADA = 1
  AND SMATRICPL.CODFILIAL = 1
  AND SHABILITACAOFILIAL.CODTIPOCURSO IN (1, 195, 196, 281, 285, 345, 357, 424)
  AND SPLETIVO.CODPERLET = '2026.1'
  AND SSTATUS.DESCRICAO IN (
      'PENDENTE PAGAMENTO',
      'PENDENTE PAGAMENTO/ADITAMENTO',
      'PENDENTE ADITAMENTO',
      'MATRICULADO (PERIODO LETIVO)',
      'TRANCADO'
  );


/* ============================================================================
   4. EMAIL INSTITUCIONAL
   ============================================================================ */

-- Gera sugestão de e-mail institucional (@discentes.uninta.edu.br) para alunos
-- ativos em cursos presenciais, no período letivo informado pelo parâmetro :CODPERLET.
-- Regras:
--   • Se o aluno tiver nome social, o primeiro nome do nome social é usado no e-mail.
--   • O "Nome de exibição" combina o primeiro nome (social ou civil) + último sobrenome.
--   • Formato do e-mail: primeirnome.RA@discentes.uninta.edu.br
SELECT
	DISTINCT
	CASE /*RETORNA SUGESTÃO DE E-MAIL INSTITUCIONAL, CASO A PESSOA POSSUA UM NOME SOCIAL O NOME SOCIAL É UTILIZADO NA COMPOSIÇÃO DO E-MAIL*/
		WHEN PPESSOA.NOMESOCIAL IS NOT NULL THEN SUBSTRING(PPESSOA.NOMESOCIAL, 1, CHARINDEX(' ', PPESSOA.NOMESOCIAL + ' ') - 1) + '.' + SALUNO.RA + '@discentes.uninta.edu.br'
		ELSE SUBSTRING(PPESSOA.NOME, 1, CHARINDEX(' ', PPESSOA.NOME + ' ') - 1) + '.' + SALUNO.RA + '@discentes.uninta.edu.br'		
	END AS [Nome de usuário],
	SUBSTRING(PPESSOA.NOME, 1, CHARINDEX(' ', PPESSOA.NOME + ' ') - 1) AS [Nome],
	RIGHT(LTRIM(RTRIM(PPESSOA.NOME)),
      CHARINDEX(' ', REVERSE(LTRIM(RTRIM(PPESSOA.NOME))) + ' ') - 1) AS [Sobrenome],
	COALESCE(
    NULLIF(SUBSTRING(LTRIM(RTRIM(PPESSOA.NOMESOCIAL)), 1,
      CHARINDEX(' ', LTRIM(RTRIM(PPESSOA.NOMESOCIAL)) + ' ') - 1), ''),
    SUBSTRING(LTRIM(RTRIM(PPESSOA.NOME)), 1,
      CHARINDEX(' ', LTRIM(RTRIM(PPESSOA.NOME)) + ' ') - 1)) + ' ' + RIGHT(LTRIM(RTRIM(PPESSOA.NOME)),
      CHARINDEX(' ', REVERSE(LTRIM(RTRIM(PPESSOA.NOME))) + ' ') - 1) 
      AS [Nome de exibição],
	'DISCENTE' AS Cargo,
	'UNINTA' AS Departamento,
	'' AS [Número comercial],
	'' AS [Telefone comercial],
	'' AS [Celular],
	'' AS [Fax],
	'' AS [Endereço de email alternativo],
	'' AS [Endereço],
	'' AS [Cidade],
	'' AS [Estado ou província],
	'' AS [CEP],
	'' AS [País ou região]
FROM HATENDIMENTOBASE WITH (NOLOCK)
JOIN HCLIENTEATENDIMENTO WITH (NOLOCK)
	ON HCLIENTEATENDIMENTO.CODCOLIGADA = HATENDIMENTOBASE.CODCOLIGADA
		AND HCLIENTEATENDIMENTO.CODLOCAL = HATENDIMENTOBASE.CODCOLIGADA
		AND HCLIENTEATENDIMENTO.CODATENDIMENTO = HATENDIMENTOBASE.CODATENDIMENTO
JOIN SALUNO WITH (NOLOCK)
	ON SALUNO.CODCOLIGADA = HCLIENTEATENDIMENTO.CODCOLIGADA
		AND SALUNO.RA = HCLIENTEATENDIMENTO.RAALUNO 
JOIN PPESSOA WITH (NOLOCK)
	ON PPESSOA.CODIGO = SALUNO.CODPESSOA
JOIN SHABILITACAOALUNO WITH (NOLOCK)
		ON SHABILITACAOALUNO.CODCOLIGADA = SALUNO.CODCOLIGADA
			AND SHABILITACAOALUNO.RA = SALUNO.RA
	JOIN SHABILITACAOFILIAL WITH (NOLOCK)
		ON SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
			AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL 
	JOIN SMATRICPL WITH (NOLOCK)
		ON SMATRICPL.CODCOLIGADA = SALUNO.CODCOLIGADA
	 		AND SMATRICPL.RA = SALUNO.RA
	JOIN SPLETIVO WITH (NOLOCK)
		ON SPLETIVO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
			AND SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
	JOIN SCURSO WITH (NOLOCK)
		ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
			AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	JOIN SSTATUS SSTATUSHABILITACAO WITH (NOLOCK)
		ON SSTATUSHABILITACAO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
			AND SSTATUSHABILITACAO.CODSTATUS = SHABILITACAOALUNO.CODSTATUS
	JOIN SSTATUS SSTATUSMATRICPL WITH (NOLOCK)
		ON SSTATUSMATRICPL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
			AND SSTATUSMATRICPL.CODSTATUS = SMATRICPL.CODSTATUS
WHERE HATENDIMENTOBASE.CODTIPOATENDIMENTO = 686
	AND SHABILITACAOFILIAL.CODCOLIGADA = :CODCOLIGADA
	AND SSTATUSHABILITACAO.DESCRICAO = 'ATIVO'
	AND SSTATUSMATRICPL.DESCRICAO IN ('MATRICULADO (PERIODO LETIVO)', 'PENDENTE PAGAMENTO', 'PENDENTE ADITAMENTO', 'PENDENTE PAGAMENTO/ADITAMENTO', 'PENDENTE PAGAMENTO/FINANC', 'PENDENTE PAGAMENTO/MINUTA')


/* ============================================================================
   5. PESSOAS E USUÁRIOS
   ============================================================================ */

-- Busca nome, CPF, RA e situação de colaborador a partir do código de usuário.
-- Usa ROW_NUMBER para evitar duplicatas em caso de múltiplos vínculos em PFUNC
-- (prioriza situação 'A' = Ativo quando há mais de um registro).
SELECT
    PPESSOA.CODUSUARIO AS USUARIO,
    PPESSOA.NOME,
    PPESSOA.CPF,
    SALUNO.RA,
    PFUNC.CODSITUACAO  AS STATUS_COLABORADOR
FROM PPESSOA WITH (NOLOCK)
LEFT JOIN SALUNO WITH (NOLOCK)
    ON SALUNO.CODPESSOA = PPESSOA.CODIGO
LEFT JOIN (
    SELECT
        CODPESSOA,
        CODSITUACAO,
        ROW_NUMBER() OVER (
            PARTITION BY CODPESSOA
            ORDER BY CASE WHEN CODSITUACAO = 'A' THEN 0 ELSE 1 END
        ) AS RN
    FROM PFUNC WITH (NOLOCK)
) PFUNC
    ON PFUNC.CODPESSOA = PPESSOA.CODIGO
   AND PFUNC.RN = 1
WHERE PPESSOA.CODUSUARIO = '2022118497';
-- OU use: WHERE PPESSOA.CODUSUARIO LIKE '%parte_do_usuario%'


-- Busca nome, CPF, RA e indica se a pessoa é colaboradora (com status detalhado).
-- Observação: pode retornar duplicatas se houver múltiplos vínculos em PFUNC.
SELECT
    PPESSOA.CODUSUARIO AS USUARIO,
    PPESSOA.NOME,
    PPESSOA.CPF,
    SALUNO.RA,
    CASE WHEN PFUNC.CODPESSOA IS NOT NULL THEN 'SIM' ELSE 'NÃO' END AS COLABORADOR,
    PFUNC.CODSITUACAO AS STATUS_COLABORADOR,
    CASE
        WHEN PFUNC.CODSITUACAO = 'A' THEN 'ATIVO'
        WHEN PFUNC.CODSITUACAO IS NOT NULL THEN 'INATIVO'
        ELSE NULL
    END AS DESC_STATUS
FROM PPESSOA WITH (NOLOCK)
LEFT JOIN SALUNO WITH (NOLOCK)
    ON SALUNO.CODPESSOA = PPESSOA.CODIGO
LEFT JOIN PFUNC WITH (NOLOCK)
    ON PFUNC.CODPESSOA = PPESSOA.CODIGO
WHERE PPESSOA.CODUSUARIO = '1-03667';


-- Perfil completo de um usuário: verifica se é aluno e/ou colaborador, retornando
-- RA, seção/categoria e cargo do colaborador (quando houver).
-- Usa ROW_NUMBER para priorizar o vínculo ativo e subquery para garantir RA único.
-- Usa parâmetro :CODUSUARIO.
SELECT
    GUSUARIO.CODUSUARIO,
    PPESSOA.NOME,
    PPESSOA.CPF,
    CASE WHEN SALUNO_UNIQ.RA IS NOT NULL        THEN 'SIM' ELSE 'NÃO' END AS ALUNO,
    SALUNO_UNIQ.RA,
    CASE WHEN PFUNC_PRINCIPAL.CODPESSOA IS NOT NULL THEN 'SIM' ELSE 'NÃO' END AS COLABORADOR,
    CASE
        WHEN PFUNC_PRINCIPAL.CODSITUACAO = 'A' THEN 'ATIVO'
        WHEN PFUNC_PRINCIPAL.CODSITUACAO = 'D' THEN 'DEMITIDO'
        ELSE PFUNC_PRINCIPAL.CODSITUACAO
    END AS STATUS_COLABORADOR,
    PSECAO.DESCRICAO  AS CATEGORIA_COLABORADOR,
    PFUNCAO.NOME      AS CARGO
FROM GUSUARIO WITH (NOLOCK)
    JOIN PPESSOA WITH (NOLOCK)
        ON PPESSOA.CODUSUARIO = GUSUARIO.CODUSUARIO
    /* Verifica se é aluno (pega o primeiro RA para evitar duplicatas) */
    LEFT JOIN (
        SELECT CODPESSOA, MIN(RA) AS RA
        FROM SALUNO WITH (NOLOCK)
        WHERE CODCOLIGADA = 1
        GROUP BY CODPESSOA
    ) AS SALUNO_UNIQ
        ON SALUNO_UNIQ.CODPESSOA = PPESSOA.CODIGO
    /* Verifica se é colaborador (prioriza situação Ativa) */
    LEFT JOIN (
        SELECT
            CODPESSOA,
            CODCOLIGADA,
            CODSECAO,
            CODFUNCAO,
            CODSITUACAO,
            ROW_NUMBER() OVER (
                PARTITION BY CODPESSOA
                ORDER BY CASE WHEN CODSITUACAO = 'A' THEN 0 ELSE 1 END
            ) AS RN
        FROM PFUNC WITH (NOLOCK)
        WHERE CODCOLIGADA = 1
    ) AS PFUNC_PRINCIPAL
        ON PFUNC_PRINCIPAL.CODPESSOA = PPESSOA.CODIGO
       AND PFUNC_PRINCIPAL.RN = 1
    /* Seção/categoria do colaborador (ex: Professor, Serviços Gerais...) */
    LEFT JOIN PSECAO WITH (NOLOCK)
        ON PSECAO.CODCOLIGADA = PFUNC_PRINCIPAL.CODCOLIGADA
       AND PSECAO.CODIGO      = PFUNC_PRINCIPAL.CODSECAO
    /* Cargo do colaborador */
    LEFT JOIN PFUNCAO WITH (NOLOCK)
        ON PFUNCAO.CODCOLIGADA = PFUNC_PRINCIPAL.CODCOLIGADA
       AND PFUNCAO.CODIGO      = PFUNC_PRINCIPAL.CODFUNCAO
WHERE GUSUARIO.CODUSUARIO = :CODUSUARIO;


-- Perfil completo do usuário com verificação de acesso ao Portal do RH.
-- Retorna se o usuário é aluno e/ou colaborador, o cargo/seção e indica
-- permissões fun_web (portal) e fun_web_pto (ponto eletrônico).
-- Status COMPLETO = tem as duas permissões; INCOMPLETO = tem apenas uma.
-- Usa parâmetro :CODUSUARIO.
SELECT
    GUSUARIO.CODUSUARIO,
    PPESSOA.NOME,
    PPESSOA.CPF,
    CASE WHEN SALUNO_UNIQ.RA IS NOT NULL THEN 'SIM' ELSE 'NÃO' END AS ALUNO,
    SALUNO_UNIQ.RA,
    CASE WHEN PFUNC_PRINCIPAL.CODPESSOA IS NOT NULL THEN 'SIM' ELSE 'NÃO' END AS COLABORADOR,
    CASE
        WHEN PFUNC_PRINCIPAL.CODSITUACAO = 'A' THEN 'ATIVO'
        WHEN PFUNC_PRINCIPAL.CODSITUACAO = 'D' THEN 'DEMITIDO'
        ELSE PFUNC_PRINCIPAL.CODSITUACAO
    END AS STATUS_COLABORADOR,
    PSECAO.DESCRICAO AS CATEGORIA_COLABORADOR,
    PFUNCAO.NOME AS CARGO,
    /* fun_web = acesso ao portal; fun_web_pto = acesso ao ponto eletrônico */
    CASE WHEN ISNULL(PERMS_RH.TEM_FUN_WEB, 0)     = 1 THEN 'SIM' ELSE 'NÃO' END AS PERMISSAO_FUN_WEB,
    CASE WHEN ISNULL(PERMS_RH.TEM_FUN_WEB_PTO, 0) = 1 THEN 'SIM' ELSE 'NÃO' END AS PERMISSAO_FUN_WEB_PTO,
    CASE
        WHEN ISNULL(PERMS_RH.TEM_FUN_WEB, 0) = 1
         AND ISNULL(PERMS_RH.TEM_FUN_WEB_PTO, 0) = 1 THEN 'COMPLETO'
        WHEN ISNULL(PERMS_RH.TEM_FUN_WEB, 0) = 1
          OR ISNULL(PERMS_RH.TEM_FUN_WEB_PTO, 0) = 1 THEN 'INCOMPLETO'
        ELSE 'NÃO'
    END AS ACESSO_PORTAL_RH
FROM GUSUARIO WITH (NOLOCK)
    JOIN PPESSOA WITH (NOLOCK)
        ON PPESSOA.CODUSUARIO = GUSUARIO.CODUSUARIO
    LEFT JOIN (
        SELECT CODPESSOA, MIN(RA) AS RA
        FROM SALUNO WITH (NOLOCK)
        WHERE CODCOLIGADA = 1
        GROUP BY CODPESSOA
    ) AS SALUNO_UNIQ
        ON SALUNO_UNIQ.CODPESSOA = PPESSOA.CODIGO
    LEFT JOIN (
        SELECT
            CODPESSOA,
            CODCOLIGADA,
            CODSECAO,
            CODFUNCAO,
            CODSITUACAO,
            ROW_NUMBER() OVER (
                PARTITION BY CODPESSOA
                ORDER BY CASE WHEN CODSITUACAO = 'A' THEN 0 ELSE 1 END
            ) AS RN
        FROM PFUNC WITH (NOLOCK)
        WHERE CODCOLIGADA = 1
    ) AS PFUNC_PRINCIPAL
        ON PFUNC_PRINCIPAL.CODPESSOA = PPESSOA.CODIGO
       AND PFUNC_PRINCIPAL.RN = 1
    LEFT JOIN PSECAO WITH (NOLOCK)
        ON PSECAO.CODCOLIGADA = PFUNC_PRINCIPAL.CODCOLIGADA
       AND PSECAO.CODIGO      = PFUNC_PRINCIPAL.CODSECAO
    LEFT JOIN PFUNCAO WITH (NOLOCK)
        ON PFUNCAO.CODCOLIGADA = PFUNC_PRINCIPAL.CODCOLIGADA
       AND PFUNCAO.CODIGO      = PFUNC_PRINCIPAL.CODFUNCAO
    LEFT JOIN (
        SELECT
            CODUSUARIO,
            MAX(CASE WHEN CODPERFIL = 'fun_web'     THEN 1 ELSE 0 END) AS TEM_FUN_WEB,
            MAX(CASE WHEN CODPERFIL = 'fun_web_pto' THEN 1 ELSE 0 END) AS TEM_FUN_WEB_PTO
        FROM GUSRPERFIL WITH (NOLOCK)
        WHERE CODPERFIL IN ('fun_web', 'fun_web_pto')
        GROUP BY CODUSUARIO
    ) AS PERMS_RH
        ON PERMS_RH.CODUSUARIO = GUSUARIO.CODUSUARIO
WHERE GUSUARIO.CODUSUARIO = :CODUSUARIO;


/* ============================================================================
   6. PROFESSORES
   ============================================================================ */

-- Lista os polos de atuação de um professor, incluindo indicador de permissão
-- de acesso ao polo (verifica via SUSUARIOFILIAL).
-- Usa parâmetros :$CODCOLIGADA e :CODPROF.
SELECT DISTINCT
    SPROFESSOR.CODPROF      AS CODIGO_PROFESSOR,
    PPESSOA.NOME            AS NOME_PROFESSOR,
    SCURSO.NOME             AS CURSO,
    SPLETIVO.CODPERLET,
    CONCAT(
        STIPOCURSO.CODTIPOCURSO, ' - ',
        STIPOCURSO.NOME,
        CASE WHEN ZMDPOLOS.CODINEP IS NOT NULL THEN CONCAT(' (', ZMDPOLOS.CODINEP, ')') END,
        CASE WHEN NOT EXISTS (
                SELECT 1
                FROM SUSUARIOFILIAL WITH (NOLOCK)
                WHERE SUSUARIOFILIAL.CODCOLIGADA  = SHABILITACAOFILIAL.CODCOLIGADA
                  AND SUSUARIOFILIAL.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
                  AND SUSUARIOFILIAL.CODFILIAL    = SHABILITACAOFILIAL.CODFILIAL
                  AND SUSUARIOFILIAL.CODUSUARIO   = PPESSOA.CODUSUARIO
             ) THEN ' SEM PERMISSÃO'
        END
    ) AS POLO
FROM SPROFESSOR WITH (NOLOCK)
    JOIN PPESSOA WITH (NOLOCK)
        ON PPESSOA.CODIGO = SPROFESSOR.CODPESSOA
    JOIN SPROFESSORTURMA WITH (NOLOCK)
        ON SPROFESSORTURMA.CODCOLIGADA = SPROFESSOR.CODCOLIGADA
       AND SPROFESSORTURMA.CODPROF     = SPROFESSOR.CODPROF
    JOIN STURMADISC WITH (NOLOCK)
        ON STURMADISC.CODCOLIGADA  = SPROFESSORTURMA.CODCOLIGADA
       AND STURMADISC.IDTURMADISC  = SPROFESSORTURMA.IDTURMADISC
    JOIN SHABILITACAOFILIAL WITH (NOLOCK)
        ON SHABILITACAOFILIAL.CODCOLIGADA         = STURMADISC.CODCOLIGADA
       AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL  = STURMADISC.IDHABILITACAOFILIAL
    JOIN STIPOCURSO WITH (NOLOCK)
        ON STIPOCURSO.CODCOLIGADA  = SHABILITACAOFILIAL.CODCOLIGADA
       AND STIPOCURSO.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
    LEFT JOIN ZMDPOLOS WITH (NOLOCK)
        ON ZMDPOLOS.CODCOLIGADA = STIPOCURSO.CODCOLIGADA
       AND ZMDPOLOS.CODPOLO     = STIPOCURSO.CODTIPOCURSO
    JOIN SHABILITACAO WITH (NOLOCK)
        ON SHABILITACAO.CODCOLIGADA     = SHABILITACAOFILIAL.CODCOLIGADA
       AND SHABILITACAO.CODCURSO        = SHABILITACAOFILIAL.CODCURSO
       AND SHABILITACAO.CODHABILITACAO  = SHABILITACAOFILIAL.CODHABILITACAO
    JOIN SCURSO WITH (NOLOCK)
        ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
       AND SCURSO.CODCURSO    = SHABILITACAOFILIAL.CODCURSO
    JOIN SPLETIVO WITH (NOLOCK)
        ON SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA
       AND SPLETIVO.IDPERLET    = STURMADISC.IDPERLET
WHERE SPROFESSOR.CODCOLIGADA = :$CODCOLIGADA
  AND SPROFESSOR.CODPROF     = :CODPROF;


-- Lista as disciplinas, turmas e polos de um professor por período letivo.
-- Inclui nome da disciplina, da turma e status de permissão de acesso ao polo.
-- Usa parâmetros :$CODCOLIGADA e :CODPROF.
SELECT DISTINCT
    SPROFESSOR.CODPROF,
    PPESSOA.NOME,
    SCURSO.NOME             AS SCURSO,
    SPLETIVO.CODPERLET,
    SDISCIPLINA.NOME        AS DISCIPLINA,
    STURMA.NOME             AS TURMA,
    CONCAT(
        STIPOCURSO.CODTIPOCURSO, ' - ',
        STIPOCURSO.NOME,
        CASE WHEN ZMDPOLOS.CODINEP IS NOT NULL THEN CONCAT(' (', ZMDPOLOS.CODINEP, ')') END,
        CASE WHEN NOT EXISTS (
                SELECT 1
                FROM SUSUARIOFILIAL WITH (NOLOCK)
                WHERE SUSUARIOFILIAL.CODCOLIGADA  = SHABILITACAOFILIAL.CODCOLIGADA
                  AND SUSUARIOFILIAL.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
                  AND SUSUARIOFILIAL.CODFILIAL    = SHABILITACAOFILIAL.CODFILIAL
                  AND SUSUARIOFILIAL.CODUSUARIO   = PPESSOA.CODUSUARIO
             ) THEN ' SEM PERMISSÃO'
        END
    ) AS POLO
FROM SPROFESSOR WITH (NOLOCK)
    JOIN PPESSOA WITH (NOLOCK)
        ON PPESSOA.CODIGO = SPROFESSOR.CODPESSOA
    JOIN SPROFESSORTURMA WITH (NOLOCK)
        ON SPROFESSORTURMA.CODCOLIGADA = SPROFESSOR.CODCOLIGADA
       AND SPROFESSORTURMA.CODPROF     = SPROFESSOR.CODPROF
    JOIN STURMADISC WITH (NOLOCK)
        ON STURMADISC.CODCOLIGADA  = SPROFESSORTURMA.CODCOLIGADA
       AND STURMADISC.IDTURMADISC  = SPROFESSORTURMA.IDTURMADISC
    JOIN SHABILITACAOFILIAL WITH (NOLOCK)
        ON SHABILITACAOFILIAL.CODCOLIGADA         = STURMADISC.CODCOLIGADA
       AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL  = STURMADISC.IDHABILITACAOFILIAL
    JOIN STIPOCURSO WITH (NOLOCK)
        ON STIPOCURSO.CODCOLIGADA  = SHABILITACAOFILIAL.CODCOLIGADA
       AND STIPOCURSO.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
    LEFT JOIN ZMDPOLOS WITH (NOLOCK)
        ON ZMDPOLOS.CODCOLIGADA = STIPOCURSO.CODCOLIGADA
       AND ZMDPOLOS.CODPOLO     = STIPOCURSO.CODTIPOCURSO
    JOIN SHABILITACAO WITH (NOLOCK)
        ON SHABILITACAO.CODCOLIGADA     = SHABILITACAOFILIAL.CODCOLIGADA
       AND SHABILITACAO.CODCURSO        = SHABILITACAOFILIAL.CODCURSO
       AND SHABILITACAO.CODHABILITACAO  = SHABILITACAOFILIAL.CODHABILITACAO
    JOIN SCURSO WITH (NOLOCK)
        ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
       AND SCURSO.CODCURSO    = SHABILITACAOFILIAL.CODCURSO
    JOIN SDISCIPLINA WITH (NOLOCK)
        ON SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
       AND SDISCIPLINA.CODDISC     = STURMADISC.CODDISC
    JOIN STURMA WITH (NOLOCK)
        ON STURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA
       AND STURMA.CODTURMA    = STURMADISC.CODTURMA
    JOIN SPLETIVO WITH (NOLOCK)
        ON SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA
       AND SPLETIVO.IDPERLET    = STURMADISC.IDPERLET
WHERE SPROFESSOR.CODCOLIGADA = :$CODCOLIGADA
  AND SPROFESSOR.CODPROF     = :CODPROF;


/* ============================================================================
   7. ATENDIMENTOS
   ============================================================================ */

-- Lista atendimentos de Transferência Interna (código 113), exibindo
-- o texto da solicitação, curso, polo e período letivo do aluno.
SELECT
    1 AS QTD,
    HATENDIMENTOBASE.CODATENDIMENTO,
    CASE HATENDIMENTOBASE.CODTIPOATENDIMENTO
        WHEN '113' THEN 'Transferencia Interna'
    END AS ATENDIMENTO,
    SALUNO.RA,
    SPLETIVO.CODPERLET,
    SCURSO.CODCURSO,
    SCURSO.NOME                   AS CURSO,
    HSOLICITACAO.TEXTOSOLICITACAO AS [SOLICITAÇÃO],
    PPESSOA.NOME,
    STIPOCURSO.NOME               AS IES
FROM HATENDIMENTOBASE WITH (NOLOCK)
    JOIN SATENDIMENTO WITH (NOLOCK)
        ON SATENDIMENTO.CODCOLIGADA    = HATENDIMENTOBASE.CODCOLIGADA
       AND SATENDIMENTO.CODATENDIMENTO = HATENDIMENTOBASE.CODATENDIMENTO
       AND SATENDIMENTO.CODLOCAL       = HATENDIMENTOBASE.CODLOCAL
    JOIN SALUNO WITH (NOLOCK)
        ON SALUNO.CODCOLIGADA = SATENDIMENTO.CODCOLIGADA
       AND SALUNO.RA          = SATENDIMENTO.RA
    JOIN SHABILITACAOFILIAL WITH (NOLOCK)
        ON SHABILITACAOFILIAL.CODCOLIGADA         = SATENDIMENTO.CODCOLIGADA
       AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL  = SATENDIMENTO.IDHABILITACAOFILIAL
    JOIN SCURSO WITH (NOLOCK)
        ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
       AND SCURSO.CODCURSO    = SHABILITACAOFILIAL.CODCURSO
    JOIN SPLETIVO WITH (NOLOCK)
        ON SPLETIVO.CODCOLIGADA = SATENDIMENTO.CODCOLIGADA
       AND SPLETIVO.IDPERLET   = SATENDIMENTO.IDPERLET
    JOIN PPESSOA WITH (NOLOCK)
        ON PPESSOA.CODIGO = SALUNO.CODPESSOA
    JOIN STIPOCURSO WITH (NOLOCK)
        ON STIPOCURSO.CODCOLIGADA  = SALUNO.CODCOLIGADA
       AND STIPOCURSO.CODTIPOCURSO = SALUNO.CODTIPOCURSO
    JOIN HSOLICITACAO WITH (NOLOCK)
        ON HSOLICITACAO.CODCOLIGADA    = HATENDIMENTOBASE.CODCOLIGADA
       AND HSOLICITACAO.CODATENDIMENTO = HATENDIMENTOBASE.CODATENDIMENTO
       AND HSOLICITACAO.CODLOCAL       = HATENDIMENTOBASE.CODLOCAL
WHERE HATENDIMENTOBASE.CODCOLIGADA = 1
  AND HATENDIMENTOBASE.CODTIPOATENDIMENTO IN (113);


-- Lista atendimentos acadêmicos: trancamento, desistência, transferência externa,
-- matrícula institucional e transferência interna.
-- Exibe o motivo declarado pelo aluno, mapeando corretamente os códigos de parâmetro
-- (o mapeamento de motivos difere para transferência interna vs. demais tipos).
SELECT
    1 AS QTD,
    HATENDIMENTOBASE.CODATENDIMENTO,
    CASE HATENDIMENTOBASE.CODTIPOATENDIMENTO
        WHEN 180 THEN 'Trancamento de Matrícula'
        WHEN 58  THEN 'Trancamento de Matrícula'
        WHEN 181 THEN 'Desistência Formalizada'
        WHEN 59  THEN 'Desistência Formalizada'
        WHEN 183 THEN 'Transferência Externa'
        WHEN 49  THEN 'Transferência Externa'
        WHEN 182 THEN 'Matrícula Institucional'
        WHEN 60  THEN 'Matrícula Institucional'
        WHEN 82  THEN 'Transferência Interna'
    END AS ATENDIMENTO,
    CASE
        WHEN HATENDIMENTOBASE.CODTIPOATENDIMENTO = 82 THEN
            CASE HPARAMATENDIMENTO.VALOR
                WHEN '1' THEN 'Financeiro'
                WHEN '2' THEN 'Trabalho'
                WHEN '3' THEN 'Mudança de Domicilio'
                WHEN '4' THEN 'Não se Identificou com o curso'
                WHEN '5' THEN 'Descontentamento com o curso'
            END
        ELSE
            CASE HPARAMATENDIMENTO.VALOR
                WHEN '1' THEN 'FINANCEIRO'
                WHEN '2' THEN 'SAÚDE'
                WHEN '3' THEN 'TRABALHO'
                WHEN '4' THEN 'MUDANÇA DE DOMICÍLIO'
                WHEN '5' THEN 'NÃO SE IDENTIFICOU COM O CURSO'
                WHEN '6' THEN 'PESSOAL/FAMILIAR'
                WHEN '7' THEN 'ENSINO REMOTO/PANDEMIA'
                WHEN '8' THEN 'REGULARIZAR SITUAÇÃO JUNTO A IES'
                WHEN '9' THEN 'OUTROS'
            END
    END AS MOTIVO,
    SALUNO.RA,
    SPLETIVO.CODPERLET,
    SCURSO.CODCURSO,
    SCURSO.NOME                   AS CURSO,
    HSOLICITACAO.TEXTOSOLICITACAO AS [SOLICITAÇÃO],
    PPESSOA.NOME,
    STIPOCURSO.NOME               AS IES
FROM HATENDIMENTOBASE WITH (NOLOCK)
    JOIN HPARAMATENDIMENTO WITH (NOLOCK)
        ON HATENDIMENTOBASE.CODCOLIGADA    = HPARAMATENDIMENTO.CODCOLIGADA
       AND HATENDIMENTOBASE.CODATENDIMENTO = HPARAMATENDIMENTO.CODATENDIMENTO
       AND HPARAMATENDIMENTO.CODPARAMETRO IN (61, 63, 65, 67, 282)
    JOIN SATENDIMENTO WITH (NOLOCK)
        ON SATENDIMENTO.CODCOLIGADA    = HATENDIMENTOBASE.CODCOLIGADA
       AND SATENDIMENTO.CODATENDIMENTO = HATENDIMENTOBASE.CODATENDIMENTO
       AND SATENDIMENTO.CODLOCAL       = HATENDIMENTOBASE.CODLOCAL
    JOIN SALUNO WITH (NOLOCK)
        ON SALUNO.CODCOLIGADA = SATENDIMENTO.CODCOLIGADA
       AND SALUNO.RA          = SATENDIMENTO.RA
    JOIN SHABILITACAOFILIAL WITH (NOLOCK)
        ON SHABILITACAOFILIAL.CODCOLIGADA         = SATENDIMENTO.CODCOLIGADA
       AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL  = SATENDIMENTO.IDHABILITACAOFILIAL
    JOIN SCURSO WITH (NOLOCK)
        ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
       AND SCURSO.CODCURSO    = SHABILITACAOFILIAL.CODCURSO
    JOIN SPLETIVO WITH (NOLOCK)
        ON SPLETIVO.CODCOLIGADA = SATENDIMENTO.CODCOLIGADA
       AND SPLETIVO.IDPERLET   = SATENDIMENTO.IDPERLET
    JOIN PPESSOA WITH (NOLOCK)
        ON PPESSOA.CODIGO = SALUNO.CODPESSOA
    JOIN STIPOCURSO WITH (NOLOCK)
        ON STIPOCURSO.CODCOLIGADA  = SALUNO.CODCOLIGADA
       AND STIPOCURSO.CODTIPOCURSO = SALUNO.CODTIPOCURSO
    JOIN HSOLICITACAO WITH (NOLOCK)
        ON HSOLICITACAO.CODCOLIGADA    = HATENDIMENTOBASE.CODCOLIGADA
       AND HSOLICITACAO.CODATENDIMENTO = HATENDIMENTOBASE.CODATENDIMENTO
       AND HSOLICITACAO.CODLOCAL       = HATENDIMENTOBASE.CODLOCAL
WHERE HATENDIMENTOBASE.CODCOLIGADA = 1
  AND HATENDIMENTOBASE.CODTIPOATENDIMENTO IN (180, 58, 181, 59, 183, 49, 182, 60, 82);


/* ============================================================================
   8. DESEMPENHO ACADÊMICO
   ============================================================================ */

-- Calcula percentuais e totais de aprovação, reprovação por nota e por falta,
-- agrupados por curso e período letivo.
-- A subconsulta calcula os índices por IDTURMADISC; a consulta externa agrega por curso.
-- Usa parâmetros :$CODCOLIGADA, :PERIODOLETIVO e :$CODTIPOCURSO.
SELECT
    TA.CURSO,
    TA.PERIODOLETIVO,
    CONVERT(DECIMAL(18, 2), AVG(TA.PORC_APROV))                                               AS MEDIA_PERC_APROV,
    CONVERT(DECIMAL(18, 2), AVG(TA.PORC_REPROV))                                              AS MEDIA_PERC_REPROV_NOTAS,
    CONVERT(DECIMAL(18, 2), AVG(TA.PORC_REPROV_FALTA))                                        AS MEDIA_PERC_REPROV_FALTAS,
    CONVERT(DECIMAL(18, 2), AVG(TA.PORC_REPROV_FALTA) + AVG(TA.PORC_REPROV))                 AS MEDIA_PERC_REPROV_TOTAL,
    CONVERT(DECIMAL(18, 2), 100 - AVG(TA.PORC_APROV) - AVG(TA.PORC_REPROV) - AVG(TA.PORC_REPROV_FALTA)) AS OUTROS,
    SUM(TA.ABS_APROV)                                                                         AS TOTAL_APROVADOS,
    SUM(TA.ABS_REPROV)                                                                        AS TOTAL_REPROVADOS_NOTA,
    SUM(TA.ABS_REPROV_FALTA)                                                                  AS TOTAL_REPROVADOS_FALTA,
    SUM(TA.ABS_REPROV + TA.ABS_REPROV_FALTA)                                                  AS TOTAL_REPROVADOS,
    SUM(TA.OUTROS)                                                                            AS TOTAL_OUTROS,
    SUM(TA.TOTAL)                                                                             AS TOTAL_GERAL
FROM (
    SELECT
        STD.IDTURMADISC,
        SP.CODPERLET  AS PERIODOLETIVO,
        SC.NOME       AS CURSO,
        SD.NOME       AS DISCIPLINA,
        ROUND(CAST(
            (SELECT 10000 * COUNT(SM.RA) FROM SMATRICULA SM (NOLOCK)
             WHERE SM.IDTURMADISC = STD.IDTURMADISC AND SM.CODCOLIGADA = STD.CODCOLIGADA AND SM.CODSTATUS = 10)
            / NULLIF((SELECT COUNT(*) FROM SMATRICULA SM2 (NOLOCK)
                      WHERE SM2.IDTURMADISC = STD.IDTURMADISC AND SM2.CODCOLIGADA = STD.CODCOLIGADA), 0)
        AS DECIMAL(9, 4)) / 100, 2) AS PORC_REPROV,
        (SELECT COUNT(SM.RA) FROM SMATRICULA SM (NOLOCK)
         WHERE SM.IDTURMADISC = STD.IDTURMADISC AND SM.CODCOLIGADA = STD.CODCOLIGADA AND SM.CODSTATUS = 10) AS ABS_REPROV,
        ROUND(CAST(
            (SELECT 10000 * COUNT(SM.RA) FROM SMATRICULA SM (NOLOCK)
             WHERE SM.IDTURMADISC = STD.IDTURMADISC AND SM.CODCOLIGADA = STD.CODCOLIGADA AND SM.CODSTATUS = 4319)
            / NULLIF((SELECT COUNT(*) FROM SMATRICULA SM2 (NOLOCK)
                      WHERE SM2.IDTURMADISC = STD.IDTURMADISC AND SM2.CODCOLIGADA = STD.CODCOLIGADA), 0)
        AS DECIMAL(9, 4)) / 100, 2) AS PORC_REPROV_FALTA,
        (SELECT COUNT(SM.RA) FROM SMATRICULA SM (NOLOCK)
         WHERE SM.IDTURMADISC = STD.IDTURMADISC AND SM.CODCOLIGADA = STD.CODCOLIGADA AND SM.CODSTATUS = 4319) AS ABS_REPROV_FALTA,
        ROUND(CAST(
            (SELECT 10000 * COUNT(SM.RA) FROM SMATRICULA SM (NOLOCK)
             WHERE SM.IDTURMADISC = STD.IDTURMADISC AND SM.CODCOLIGADA = STD.CODCOLIGADA AND SM.CODSTATUS = 1)
            / NULLIF((SELECT COUNT(RA) FROM SMATRICULA SM2 (NOLOCK)
                      WHERE SM2.IDTURMADISC = STD.IDTURMADISC AND SM2.CODCOLIGADA = STD.CODCOLIGADA), 0)
        AS DECIMAL(9, 4)) / 100, 2) AS PORC_APROV,
        (SELECT COUNT(SM.RA) FROM SMATRICULA SM (NOLOCK)
         WHERE SM.IDTURMADISC = STD.IDTURMADISC AND SM.CODCOLIGADA = STD.CODCOLIGADA AND SM.CODSTATUS = 1) AS ABS_APROV,
        (SELECT COUNT(SM.RA) FROM SMATRICULA SM (NOLOCK)
         WHERE SM.IDTURMADISC = STD.IDTURMADISC AND SM.CODCOLIGADA = STD.CODCOLIGADA
           AND SM.CODSTATUS NOT IN (1, 10, 4319)) AS OUTROS,
        (SELECT COUNT(*) FROM SMATRICULA SM2 (NOLOCK)
         WHERE SM2.IDTURMADISC = STD.IDTURMADISC AND SM2.CODCOLIGADA = STD.CODCOLIGADA) AS TOTAL
    FROM STURMADISC STD (NOLOCK)
        JOIN SDISCIPLINA SD (NOLOCK)
            ON STD.CODCOLIGADA = SD.CODCOLIGADA
           AND STD.CODDISC     = SD.CODDISC
        JOIN SPLETIVO SP (NOLOCK)
            ON SP.CODCOLIGADA = STD.CODCOLIGADA
           AND SP.IDPERLET    = STD.IDPERLET
        JOIN SHABILITACAOFILIAL SHAF (NOLOCK)
            ON SHAF.CODCOLIGADA          = STD.CODCOLIGADA
           AND SHAF.IDHABILITACAOFILIAL  = STD.IDHABILITACAOFILIAL
        JOIN SCURSO SC (NOLOCK)
            ON SC.CODCOLIGADA = SHAF.CODCOLIGADA
           AND SC.CODCURSO    = SHAF.CODCURSO
    WHERE SP.CODCOLIGADA   = :$CODCOLIGADA
      AND SP.CODPERLET     = :PERIODOLETIVO
      AND SC.CODTIPOCURSO  = :$CODTIPOCURSO
) AS TA
GROUP BY TA.CURSO, TA.PERIODOLETIVO
ORDER BY TA.CURSO;


/* ============================================================================
   9. LISTAS AUXILIARES
   ============================================================================ */

-- Lista de motivos para solicitações de atendimento acadêmico (uso em relatórios).
-- A opção "Outros" é sempre exibida por último; os demais itens são ordenados pelo código.
SELECT DESCRICAO, COD
FROM (
    SELECT 'Financeiro'                    AS DESCRICAO, 1 AS COD UNION ALL
    SELECT 'Trabalho'                      AS DESCRICAO, 2 AS COD UNION ALL
    SELECT 'Mudança de Domicilio'          AS DESCRICAO, 3 AS COD UNION ALL
    SELECT 'Não se Identificou com o curso' AS DESCRICAO, 4 AS COD UNION ALL
    SELECT 'Descontentamento com o curso'  AS DESCRICAO, 5 AS COD UNION ALL
    SELECT 'Outros? Especificar'           AS DESCRICAO, 9 AS COD
) TAB
ORDER BY
    CASE WHEN DESCRICAO LIKE 'Outros%' THEN 1 ELSE 0 END,
    COD;


/* ============================================================================
   10. FORMULÁRIOS E VALIDAÇÕES
   ============================================================================ */

-- Bloqueio de duplicidade na criação de e-mail institucional.
-- Retorna mensagem de erro se o aluno já possui uma solicitação do tipo 686
-- em aberto. Usado como validação em formulário do portal.
-- Parâmetros de formulário: :FRM_CMP_COLI (coligada) e :FRM_CMP_RA (RA do aluno).
SELECT DADOS.CODCOLIGADA,
       DADOS.RA,
       CASE
           WHEN EXISTS (
               SELECT TOP 1 1
               FROM HATENDIMENTOBASE HB WITH (NOLOCK)
               JOIN SATENDIMENTO SA WITH (NOLOCK)
                 ON SA.CODCOLIGADA    = HB.CODCOLIGADA
                AND SA.CODLOCAL       = HB.CODLOCAL
                AND SA.CODATENDIMENTO = HB.CODATENDIMENTO
               WHERE SA.CODCOLIGADA        = DADOS.CODCOLIGADA
                 AND SA.RA                 = DADOS.RA
                 AND HB.CODTIPOATENDIMENTO = 686
                 /* Opcional: ignorar cancelados/indeferidos */
                 -- AND HB.CODTAREFA NOT IN (:TAREFA_CANCELADO, :TAREFA_INDEFERIDO)
           )
           THEN 'VOCÊ JÁ POSSUI SOLICITAÇÃO DE CRIAÇÃO DE E-MAIL. ACOMPANHE EM SOLICITAÇÕES.'
           ELSE ''
       END AS ERRO
FROM (
    SELECT :FRM_CMP_COLI AS CODCOLIGADA,
           :FRM_CMP_RA   AS RA
) DADOS;


SELECT TOP 3 * FROM GLINKSREL WITH (NOLOCK);

SELECT MASTERTABLE, CHILDTABLE
FROM GLINKSREL WITH (NOLOCK)
ORDER BY MASTERTABLE, CHILDTABLE;

SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;

SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN (
    'PPESSOA','SALUNO','SHABILITACAOALUNO','SHABILITACAOFILIAL',
    'SCURSO','SPLETIVO','SMATRICPL','SMATRICDISC','SMATRICULA',
    'STURMADISC','SDISCIPLINA','STURMA','STURNO','SPROFESSOR',
    'SPROFESSORTURMA','SSTATUS','STIPOCURSO','GUSUARIO','PFUNC',
    'PFUNCAO','PSECAO','HATENDIMENTOBASE','SATENDIMENTO',
    'HSOLICITACAO','HPARAMATENDIMENTO','SUSUARIOFILIAL','ZMDPOLOS'
)
ORDER BY TABLE_NAME, ORDINAL_POSITION;


/

/* ============================================================================
   CONSULTA DE FILTRO PARA TOTVS
   PESQUISA TURMAS/DISCIPINAS POR USUARIO
============================================================================ */
SELECT STURMADISC.IDTURMADISC
FROM   STURMADISC WITH (NOLOCK)
       LEFT JOIN SHABILITACAOFILIAL WITH (NOLOCK)
              ON SHABILITACAOFILIAL.CODCOLIGADA         = STURMADISC.CODCOLIGADA
             AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
       LEFT JOIN SCURSO WITH (NOLOCK)
              ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
             AND SCURSO.CODCURSO    = SHABILITACAOFILIAL.CODCURSO
       LEFT JOIN STURMA WITH (NOLOCK)
              ON STURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA
             AND STURMA.CODFILIAL   = STURMADISC.CODFILIAL
             AND STURMA.CODTURMA    = STURMADISC.CODTURMA
             AND STURMA.IDPERLET    = STURMADISC.IDPERLET
       LEFT JOIN SDISCIPLINA WITH (NOLOCK)
              ON SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
             AND SDISCIPLINA.CODDISC     = STURMADISC.CODDISC
       LEFT JOIN SPLETIVO WITH (NOLOCK)
              ON SPLETIVO.CODCOLIGADA = STURMA.CODCOLIGADA
             AND SPLETIVO.IDPERLET    = STURMA.IDPERLET
       LEFT JOIN SHABILITACAO WITH (NOLOCK)
              ON SHABILITACAO.CODCOLIGADA    = SHABILITACAOFILIAL.CODCOLIGADA
             AND SHABILITACAO.CODCURSO       = SHABILITACAOFILIAL.CODCURSO
             AND SHABILITACAO.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
       LEFT JOIN SDISCGRADE WITH (NOLOCK)
              ON SDISCGRADE.CODCOLIGADA    = SHABILITACAOFILIAL.CODCOLIGADA
             AND SDISCGRADE.CODCURSO       = SHABILITACAOFILIAL.CODCURSO
             AND SDISCGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
             AND SDISCGRADE.CODGRADE       = SHABILITACAOFILIAL.CODGRADE
             AND SDISCGRADE.CODDISC        = STURMADISC.CODDISC
WHERE  STURMADISC.CODFILIAL    = 1
  AND  STURMADISC.CODTIPOCURSO = :$CODTIPOCURSO
  AND  STURMADISC.CODCOLIGADA  = :$CODCOLIGADA
  AND  (
           -- Usuário é professor desta turma-disciplina
           EXISTS (
               SELECT 1
               FROM   SPROFESSORTURMA WITH (NOLOCK)
               JOIN   SPROFESSOR WITH (NOLOCK)
                   ON SPROFESSOR.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA
                  AND SPROFESSOR.CODPROF     = SPROFESSORTURMA.CODPROF
               JOIN   PPESSOA WITH (NOLOCK)
                   ON PPESSOA.CODIGO = SPROFESSOR.CODPESSOA
               WHERE  SPROFESSORTURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA
                 AND  SPROFESSORTURMA.IDTURMADISC  = STURMADISC.IDTURMADISC
                 AND  PPESSOA.CODUSUARIO           = :CODUSUARIO
           )
           OR
           -- Usuário é aluno matriculado nesta turma-disciplina
           EXISTS (
               SELECT 1
               FROM   SMATRICULA WITH (NOLOCK)
               JOIN   SALUNO WITH (NOLOCK)
                   ON SALUNO.CODCOLIGADA = SMATRICULA.CODCOLIGADA
                  AND SALUNO.RA          = SMATRICULA.RA
               JOIN   PPESSOA WITH (NOLOCK)
                   ON PPESSOA.CODIGO = SALUNO.CODPESSOA
               WHERE  SMATRICULA.CODCOLIGADA = STURMADISC.CODCOLIGADA
                 AND  SMATRICULA.IDTURMADISC  = STURMADISC.IDTURMADISC
                 AND  PPESSOA.CODUSUARIO      = :CODUSUARIO
           )
       );


/* ============================================================================
   PROFESSORES POR NÍVEL DE ENSINO (CODTIPOCURSO = 196)
   Retorna professores distintos que possuem turmas-disciplina vinculadas
   ao nível de ensino 196, na coligada 1.
============================================================================ */
SELECT DISTINCT
    SPROFESSOR.CODPROF          AS CODIGO_PROFESSOR,
    PPESSOA.NOME                AS NOME_PROFESSOR,
    PPESSOA.CPF,
    PPESSOA.EMAIL,
    PPESSOA.CODUSUARIO,
    STIPOCURSO.NOME             AS NIVEL_ENSINO
FROM SPROFESSORTURMA WITH (NOLOCK)
    JOIN SPROFESSOR WITH (NOLOCK)
        ON SPROFESSOR.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA
       AND SPROFESSOR.CODPROF     = SPROFESSORTURMA.CODPROF
    JOIN PPESSOA WITH (NOLOCK)
        ON PPESSOA.CODIGO = SPROFESSOR.CODPESSOA
    JOIN STURMADISC WITH (NOLOCK)
        ON STURMADISC.CODCOLIGADA  = SPROFESSORTURMA.CODCOLIGADA
       AND STURMADISC.IDTURMADISC  = SPROFESSORTURMA.IDTURMADISC
    JOIN STIPOCURSO WITH (NOLOCK)
        ON STIPOCURSO.CODCOLIGADA  = STURMADISC.CODCOLIGADA
       AND STIPOCURSO.CODTIPOCURSO = STURMADISC.CODTIPOCURSO
WHERE SPROFESSORTURMA.CODCOLIGADA = 1
  AND STURMADISC.CODTIPOCURSO     = 1;


/*
MAPEAMENTO DE MODALIDADE (DIAGNOSTICO)
- Compara o que vem do polo do curso (SHABILITACAOFILIAL/STIPOCURSO/ZMDPOLOS)
- Compara o que vem da oferta da disciplina (STURMADISC.TIPO e STURMADISC.CODTIPOCURSO)
*/
SELECT TOP 200
          SALUNO.RA,
          PPESSOA.NOME AS NOMEALUNO,
          SPLETIVO.CODPERLET,
          SDISCIPLINA.CODDISC,
          SDISCIPLINA.NOME AS DISCIPLINA,
          STURMADISC.IDTURMADISC,
          STURMADISC.CODTURMA,
          STURMADISC.TIPO AS TIPO_STURMADISC,
          STURMADISC.CODTIPOCURSO AS CODTIPOCURSO_DISC,
          STIPOCURSODISC.NOME AS NOME_TIPOCURSO_DISC,
          ZMDPOLOSDISC.TIPOENSINO AS TIPOENSINO_DISC,
          ZMDPOLOSDISC.POLODIGITAL AS POLODIGITAL_DISC,
          SHABILITACAOFILIAL.CODTIPOCURSO AS CODTIPOCURSO_CURSO,
          STIPOCURSO.NOME AS NOME_TIPOCURSO_CURSO,
          ZMDPOLOS.TIPOENSINO AS TIPOENSINO_CURSO,
          ZMDPOLOS.POLODIGITAL AS POLODIGITAL_CURSO,
          CASE
                WHEN ISNULL(LTRIM(RTRIM(STURMADISC.TIPO)), '') = 'P' THEN 'Presencial'
                WHEN ISNULL(LTRIM(RTRIM(STURMADISC.TIPO)), '') = 'D' THEN 'Digital'
                WHEN ISNULL(LTRIM(RTRIM(STURMADISC.TIPO)), '') = 'E' THEN 'EAD'
                WHEN ISNULL(LTRIM(RTRIM(STURMADISC.TIPO)), '') = 'S' THEN 'Semipresencial'
                ELSE 'Nao informado'
          END AS MODALIDADE_POR_STURMADISC_TIPO,
          CASE
                WHEN ZMDPOLOSDISC.TIPOENSINO = 'P' THEN 'Presencial'
                WHEN ZMDPOLOSDISC.TIPOENSINO = 'E' AND ISNULL(ZMDPOLOSDISC.POLODIGITAL, 'N') = 'N' THEN 'Flex'
                WHEN ZMDPOLOSDISC.TIPOENSINO = 'E' AND ISNULL(ZMDPOLOSDISC.POLODIGITAL, 'N') = 'S' THEN 'Digital'
                WHEN ZMDPOLOSDISC.TIPOENSINO = 'S' THEN 'Semipresencial'
                ELSE 'Nao informado'
          END AS MODALIDADE_POR_POLO_DISC,
          CASE
                WHEN ZMDPOLOS.TIPOENSINO = 'P' THEN 'Presencial'
                WHEN ZMDPOLOS.TIPOENSINO = 'E' AND ISNULL(ZMDPOLOS.POLODIGITAL, 'N') = 'N' THEN 'Flex'
                WHEN ZMDPOLOS.TIPOENSINO = 'E' AND ISNULL(ZMDPOLOS.POLODIGITAL, 'N') = 'S' THEN 'Digital'
                WHEN ZMDPOLOS.TIPOENSINO = 'S' THEN 'Semipresencial'
                ELSE 'Nao informado'
          END AS MODALIDADE_POR_POLO_CURSO
FROM   SHABILITACAOALUNO WITH (NOLOCK)
          JOIN SALUNO WITH (NOLOCK)
             ON SALUNO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
                  AND SALUNO.RA = SHABILITACAOALUNO.RA
          JOIN PPESSOA WITH (NOLOCK)
             ON PPESSOA.CODIGO = SALUNO.CODPESSOA
          JOIN SHABILITACAOFILIAL WITH (NOLOCK)
             ON SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
                  AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
          JOIN STIPOCURSO WITH (NOLOCK)
             ON STIPOCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
                  AND STIPOCURSO.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
          LEFT JOIN ZMDPOLOS WITH (NOLOCK)
             ON ZMDPOLOS.CODCOLIGADA = STIPOCURSO.CODCOLIGADA
                  AND ZMDPOLOS.CODPOLO = STIPOCURSO.CODTIPOCURSO
          JOIN SMATRICPL WITH (NOLOCK)
             ON SMATRICPL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
                  AND SMATRICPL.RA = SHABILITACAOALUNO.RA
                  AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
          JOIN SPLETIVO WITH (NOLOCK)
             ON SPLETIVO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
                  AND SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
          JOIN SMATRICULA WITH (NOLOCK)
             ON SMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
                  AND SMATRICULA.RA = SMATRICPL.RA
                  AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET
                  AND SMATRICULA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
          JOIN STURMADISC WITH (NOLOCK)
             ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
                  AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
          JOIN SDISCIPLINA WITH (NOLOCK)
             ON SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
                  AND SDISCIPLINA.CODDISC = STURMADISC.CODDISC
          LEFT JOIN STIPOCURSO STIPOCURSODISC WITH (NOLOCK)
             ON STIPOCURSODISC.CODCOLIGADA = STURMADISC.CODCOLIGADA
                  AND STIPOCURSODISC.CODTIPOCURSO = STURMADISC.CODTIPOCURSO
          LEFT JOIN ZMDPOLOS ZMDPOLOSDISC WITH (NOLOCK)
             ON ZMDPOLOSDISC.CODCOLIGADA = STIPOCURSODISC.CODCOLIGADA
                  AND ZMDPOLOSDISC.CODPOLO = STIPOCURSODISC.CODTIPOCURSO
WHERE  SHABILITACAOALUNO.CODCOLIGADA = :$CODCOLIGADA
          AND SHABILITACAOALUNO.RA = :RA
ORDER BY SPLETIVO.CODPERLET DESC,
             STURMADISC.CODTURMA,
             SDISCIPLINA.NOME;


/* ============================================================================
   11. BIBLIOTECA
   ============================================================================ */

-- Devedores com multa pendente, agrupados por unidade bibliográfica.
-- Retorna leitor, nome e valor total de multas em aberto por biblioteca.
-- LEMPRESTIMOS.CODCLIENTE → LUSUARIO.CODIGO → PPESSOA.CODIGO (nome do devedor).
SELECT
    ISNULL(LTRIM(RTRIM(LUNIDADE.UNIDADE)), 'Sem nome')        AS UNIDADE_BIBLIOTECARIA,
    LUSUARIO.CODIGO                                           AS COD_LEITOR,
    ISNULL(LTRIM(RTRIM(PPESSOA.NOME)), '—')                   AS NOME_DEVEDOR,
    COUNT(*)                                                  AS QTD_EMPRESTIMOS_COM_MULTA,
    CONVERT(DECIMAL(18,2), SUM(LEMP.VALORMULTA))              AS VALOR_TOTAL_MULTAS
FROM LUNIDADE WITH (NOLOCK)
JOIN LEMPRESTIMOS LEMP WITH (NOLOCK)
      ON LEMP.CODCOLIGADA = LUNIDADE.CODCOLIGADA
     AND LEMP.CODUNIDADE  = LUNIDADE.CODIGO
JOIN LUSUARIO WITH (NOLOCK)
      ON LUSUARIO.CODCOLIGADA = LEMP.CODCOLIGADA
     AND LUSUARIO.CODIGO      = LEMP.CODCLIENTE
LEFT JOIN PPESSOA WITH (NOLOCK)
       ON PPESSOA.CODIGO = LUSUARIO.CODPESSOA
WHERE LUNIDADE.CODCOLIGADA = 1
  AND ISNULL(LEMP.VALORMULTA, 0) > 0
GROUP BY
    LUNIDADE.CODCOLIGADA,
    LUNIDADE.CODIGO,
    LUNIDADE.UNIDADE,
    LUSUARIO.CODIGO,
    PPESSOA.NOME
ORDER BY
    VALOR_TOTAL_MULTAS DESC,
    LUNIDADE.UNIDADE,
    PPESSOA.NOME;


/* ============================================================================
   12. AUDITORIA
   ============================================================================ */

-- Exibe todos os registros de auditoria brutos de uma turma-disciplina específica.
-- AUDITACTION 'O' = estado antes da alteração; 'U' = após; 'I' = inserção.
SELECT *
FROM TOTVSAUDIT.STURMADISC WITH (NOLOCK)
WHERE IDTURMADISC = 1495624;


-- Alterações na turma-disciplina IDTURMADISC = 1495624.
-- Mostra apenas o que mudou (campo TIPO), quem alterou e quando,
-- comparando o registro 'O' (valor anterior) com 'U' (valor novo) via AUDITID.
SELECT
    U.AUDITID           AS ID_AUDITORIA,
    U.LOGUSER           AS USUARIO,
    U.RECMODIFIEDON     AS DATA_ALTERACAO,
    O.TIPO              AS TIPO_ANTERIOR,
    U.TIPO              AS TIPO_NOVO,
    U.CODTURMA          AS TURMA,
    U.CODDISC           AS DISCIPLINA,
    U.IDPERLET          AS PERIODO
FROM TOTVSAUDIT.STURMADISC U WITH (NOLOCK)
JOIN TOTVSAUDIT.STURMADISC O WITH (NOLOCK)
    ON  O.AUDITID     = U.AUDITID
    AND O.AUDITACTION = 'O'         -- O = valor ANTES da mudança
WHERE U.AUDITACTION = 'U'           -- U = valor DEPOIS da mudança
  AND U.CODCOLIGADA = 1
  AND U.IDTURMADISC = 1495624
ORDER BY U.RECMODIFIEDON;

-- Busca IDTURMADISC para múltiplas turmas de disciplinas pelo código da turma
-- Usa lista de códigos de turma (CODTURMA) fornecida
SELECT
    STURMADISC.IDTURMADISC,
    STURMADISC.CODTURMA,
    SDISCIPLINA.CODDISC,
    SDISCIPLINA.NOME AS DISCIPLINA,
    SPLETIVO.CODPERLET,
    STURMADISC.NOME AS TURMADISC
FROM STURMADISC WITH (NOLOCK)
    JOIN SDISCIPLINA WITH (NOLOCK)
        ON SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
       AND SDISCIPLINA.CODDISC     = STURMADISC.CODDISC
    JOIN SPLETIVO WITH (NOLOCK)
        ON SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA
       AND SPLETIVO.IDPERLET    = STURMADISC.IDPERLET
WHERE STURMADISC.CODTURMA IN (
    'MED_ITAP_1º_T11_',
    'MED_ITAP_2º_T10_',
    'MED_ITAP_2º_T9_',
    'MED_ITAP_3º_T8_',
    'MED_ITAP_4º_T7_',
    'MED_ITAP_5º_T6_A',
    'MED_ITAP_5º_T6_B',
    'MED_ITAP_6º_T5_A',
    'MED_ITAP_6º_T5_B',
    'MED_ITAP_7º_T3_A',
    'MED_ITAP_7º_T3_B',
    'MED_ITAP_7º_T4_A',
    'MED_ITAP_7º_T4_B',
    'MED_ITAP_9º_T2_',
    'MED_ITAP_11º_T1_'
)
ORDER BY STURMADISC.CODTURMA, SDISCIPLINA.NOME;