SELECT  1 AS QTD,
        SINSTITUICAO.NOME AS INSTITUICAO,
        STIPOCURSO.CODTIPOCURSO, STIPOCURSO.NOME AS POLO,
        SCOMPONENTE.CODCOMPONENTE, SCOMPONENTE.DESCRICAO AS COMPONENTE,
        SMODALIDADE.CODMODALIDADE, SMODALIDADE.DESCRICAO AS MODALIDADE,
        (CASE
            WHEN TIPOENSINO = 'E' THEN 'Flex'
            WHEN TIPOENSINO = 'S' THEN 'Semipresencial'
            WHEN TIPOENSINO = 'P' THEN 'Presencial'
        END) AS [TIPOENSINO],
        (CASE
            WHEN STIPOCURSO.NOME LIKE '%SUSPENSO%' THEN 'Não'
            WHEN STIPOCURSO.NOME LIKE '%DESCREDENCIADO%' THEN 'Não'
            WHEN STIPOCURSO.NOME LIKE '%SUPERVISAO%' THEN 'Não'
            ELSE 'Sim'
        END) ATIVO
FROM    SMODALIDADE (NOLOCK)
        JOIN SCOMPONENTE (NOLOCK)
             JOIN STIPOCURSO (NOLOCK)
                  JOIN ZMDPOLOS (NOLOCK)
                       JOIN SINSTITUICAO (NOLOCK)
                         ON SINSTITUICAO.CODINST = ZMDPOLOS.CODINST 
                    ON ZMDPOLOS.CODCOLIGADA = STIPOCURSO.CODCOLIGADA 
                       AND ZMDPOLOS.CODPOLO = STIPOCURSO.CODTIPOCURSO 
               ON STIPOCURSO.CODCOLIGADA = SCOMPONENTE.CODCOLIGADA 
                  AND STIPOCURSO.CODTIPOCURSO = SCOMPONENTE.CODTIPOCURSO 
          ON SCOMPONENTE.CODCOLIGADA = SMODALIDADE.CODCOLIGADA 
             AND SCOMPONENTE.CODCOMPONENTE = SMODALIDADE.CODCOMPONENTE 