SELECT * FROM ZMDCONTRATOSFIES WITH (NOLOCK)

SELECT * FROM ZMDCONTRATOSFIESADITAMENTOS WITH (NOLOCK)

SELECT * FROM ZMDCONTRATOSFIESVALORESFIN WITH (NOLOCK)

-- ============================================================
-- CONSULTA UNIFICADA POR CPF: 048.394.173-50
-- Uma linha por semestre — contrato + aditamento + valor financeiro
-- ============================================================
SELECT ZMDCONTRATOSFIES.ID                                    AS ID_CONTRATO,
       ZMDCONTRATOSFIES.NUMCONTRATO,
       ZMDCONTRATOSFIES.TIPOPROCESSO,
       ZMDCONTRATOSFIES.DTCONTRATO,
       ZMDCONTRATOSFIES.SITCONTRATO,
       ZMDCONTRATOSFIES.CPFALUNO,
       ZMDCONTRATOSFIES.NOMEALUNO,
       ZMDCONTRATOSFIES.CODFIES,
       ZMDCONTRATOSFIES.DTNASCIMENTOALUNO,
       ZMDCONTRATOSFIES.RG,
       ZMDCONTRATOSFIES.DATAEMISSAO,
       ZMDCONTRATOSFIES.ORGAOEMISSOR,
       ZMDCONTRATOSFIES.SEXO,
       ZMDCONTRATOSFIES.ENDERECO,
       ZMDCONTRATOSFIES.BAIRRO,
       ZMDCONTRATOSFIES.CIDADE,
       ZMDCONTRATOSFIES.UF,
       ZMDCONTRATOSFIES.CEP,
       ZMDCONTRATOSFIES.TELRESIDENCIAL,
       ZMDCONTRATOSFIES.TELCELULAR,
       ZMDCONTRATOSFIES.EMAIL,
       ZMDCONTRATOSFIES.QTDSEMESTREFIN,
       ZMDCONTRATOSFIES.PERIODOFINANCIADO,
       ZMDCONTRATOSFIES.QTDSEMESTREREST,
       ZMDCONTRATOSFIES.VALORLIMITE,
       ZMDCONTRATOSFIES.PERCENTUALFIN,
       ZMDCONTRATOSFIES.TIPOFIANCA,
       ZMDCONTRATOSFIES.CNPJMANTE,
       ZMDCONTRATOSFIES.MANTENEDORA,
       ZMDCONTRATOSFIES.CODCURSO,
       ZMDCONTRATOSFIES.CURSO,
       ZMDCONTRATOSFIES.TURNO,
       ZMDCONTRATOSFIES.CODCAMPUS,
       ZMDCONTRATOSFIES.SITUACAO,
       ZMDCONTRATOSFIESADITAMENTOS.IDADITAMENTO,
       ZMDCONTRATOSFIESADITAMENTOS.SEMESTRE,
       ZMDCONTRATOSFIESADITAMENTOS.FINALIDADE,
       ZMDCONTRATOSFIESADITAMENTOS.SITUACAO             AS SITUACAO_ADITAMENTO,
       ZMDCONTRATOSFIESADITAMENTOS.TIPO,
       ZMDCONTRATOSFIESADITAMENTOS.PROUNI,
       ZMDCONTRATOSFIESADITAMENTOS.DATAINCLUSAO,
       ZMDCONTRATOSFIESADITAMENTOS.DATACONCLUSAO,
       ZMDCONTRATOSFIESVALORESFIN.IDVALORFIN,
       ZMDCONTRATOSFIESVALORESFIN.PERIODO,
       ZMDCONTRATOSFIESVALORESFIN.VALOR
FROM ZMDCONTRATOSFIES WITH (NOLOCK)
LEFT JOIN ZMDCONTRATOSFIESADITAMENTOS WITH (NOLOCK)
    ON ZMDCONTRATOSFIESADITAMENTOS.IDCONTRATO = ZMDCONTRATOSFIES.ID
LEFT JOIN ZMDCONTRATOSFIESVALORESFIN WITH (NOLOCK)
    ON ZMDCONTRATOSFIESVALORESFIN.IDCONTRATO = ZMDCONTRATOSFIES.ID
   AND ZMDCONTRATOSFIESVALORESFIN.PERIODO    = ZMDCONTRATOSFIESADITAMENTOS.SEMESTRE
WHERE ZMDCONTRATOSFIES.CPFALUNO = '065.848.193-29'
ORDER BY ZMDCONTRATOSFIESADITAMENTOS.IDADITAMENTO;