SELECT
	CASE /*RETORNA SUGESTÃO DE E-MAIL INSTITUCIONAL, CASO A PESSOA POSSUA UM NOME SOCIAL O NOME SOCIAL É UTILIZADO NA COMPOSIÇÃO DO E-MAIL*/
		WHEN PPESSOA.NOMESOCIAL IS NOT NULL THEN SUBSTRING(PPESSOA.NOMESOCIAL, 1, CHARINDEX(' ', PPESSOA.NOMESOCIAL + ' ') - 1) + '.' + SALUNO.RA + '@discentes.uninta.edu.br'
		ELSE SUBSTRING(PPESSOA.NOME, 1, CHARINDEX(' ', PPESSOA.NOME + ' ') - 1) + '.' + SALUNO.RA + '@discentes.uninta.edu.br'		
	END AS [Nome de usuário],
	SUBSTRING(PPESSOA.NOME, 1, CHARINDEX(' ', PPESSOA.NOME + ' ') - 1) AS [Nome],
	RIGHT(LTRIM(RTRIM(PPESSOA.NOME)),
      CHARINDEX(' ', REVERSE(LTRIM(RTRIM(PPESSOA.NOME))) + ' ') - 1) AS [Sobrenome],
	COALESCE(
    NULLIF(SUBSTRING(LTRIM(RTRIM(PPESSOA.NOMESOCIAL)), 1,
      CHARINDEX(' ', LTRIM(RTRIM(PPESSOA.NOMESOCIAL)) + ' ') - 1), ''),
    SUBSTRING(LTRIM(RTRIM(PPESSOA.NOME)), 1,
      CHARINDEX(' ', LTRIM(RTRIM(PPESSOA.NOME)) + ' ') - 1)) + ' ' + RIGHT(LTRIM(RTRIM(PPESSOA.NOME)),
      CHARINDEX(' ', REVERSE(LTRIM(RTRIM(PPESSOA.NOME))) + ' ') - 1) 
      AS [Nome de exibição],
	'DISCENTE' AS Cargo,
	'UNINTA' AS Departamento,
	'' AS [Número comercial],
	'' AS [Telefone comercial],
	'' AS [Celular],
	'' AS [Fax],
	'' AS [Endereço de email alternativo],
	'' AS [Endereço],
	'' AS [Cidade],
	'' AS [Estado ou província],
	'' AS [CEP],
	'' AS [País ou região]
	/*PPESSOA.NOMESOCIAL,
	SALUNO.RA,
	PPESSOA.NOME AS [NOME COMPLETO],*/
FROM SALUNO WITH (NOLOCK)
	JOIN PPESSOA WITH (NOLOCK)
		ON PPESSOA.CODIGO = SALUNO.CODPESSOA
	JOIN SHABILITACAOALUNO WITH (NOLOCK)
		ON SHABILITACAOALUNO.CODCOLIGADA = SALUNO.CODCOLIGADA
			AND SHABILITACAOALUNO.RA = SALUNO.RA
	JOIN SHABILITACAOFILIAL WITH (NOLOCK)
		ON SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
			AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL 
	JOIN SMATRICPL WITH (NOLOCK)
		ON SMATRICPL.CODCOLIGADA = SALUNO.CODCOLIGADA
	 		AND SMATRICPL.RA = SALUNO.RA
	JOIN SPLETIVO WITH (NOLOCK)
		ON SPLETIVO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
			AND SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
	JOIN SCURSO WITH (NOLOCK)
		ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
			AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	JOIN SSTATUS SSTATUSHABILITACAO WITH (NOLOCK)
		ON SSTATUSHABILITACAO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
			AND SSTATUSHABILITACAO.CODSTATUS = SHABILITACAOALUNO.CODSTATUS
	JOIN SSTATUS SSTATUSMATRICPL WITH (NOLOCK)
		ON SSTATUSMATRICPL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
			AND SSTATUSMATRICPL.CODSTATUS = SMATRICPL.CODSTATUS
WHERE
	SHABILITACAOFILIAL.CODCOLIGADA = 1
	AND SPLETIVO.CODTIPOCURSO NOT IN (2, 5, 195, 196, 285, 281, 424, 345, 357)
	AND SSTATUSHABILITACAO.DESCRICAO = 'ATIVO'
	AND SPLETIVO.CODPERLET = :CODPERLET
	AND SSTATUSMATRICPL.DESCRICAO IN ('MATRICULADO (PERIODO LETIVO)', 'PENDENTE PAGAMENTO', 'PENDENTE ADITAMENTO', 'PENDENTE PAGAMENTO/ADITAMENTO')