SELECT
    SALUNO.RA,
    PPESSOA.NOME,
    PPESSOA.CPF
FROM PPESSOA WITH (NOLOCK)
JOIN SALUNO WITH (NOLOCK)
    ON SALUNO.CODPESSOA = PPESSOA.CODIGO
WHERE PPESSOA.CPF = '13334582744';

SELECT  CONCAT(SALUNO.RA, ' - ', PPESSOA.NOME, ' (', PPESSOA.CPF, ')') AS [ALUNO(A)],
	    SPLETIVO.IDPERLET,
        /* STIPOCURSO.CODTIPOCURSO AS COD_POLO, */
        /*(CASE
            WHEN ZMDPOLOS.CODINEP IS NULL THEN STIPOCURSO.NOME
            ELSE CONCAT(STIPOCURSO.NOME, ' (', ZMDPOLOS.CODINEP, ')')
        END)                    AS POLO,*/
        CONCAT(
        	STIPOCURSO.CODTIPOCURSO, ' - ',
            STIPOCURSO.NOME, (CASE WHEN ZMDPOLOS.CODINEP IS NOT NULL THEN CONCAT(' (', ZMDPOLOS.CODINEP, ')') END),
            (CASE
                WHEN NOT EXISTS (
                    SELECT  1
                    FROM    SUSUARIOFILIAL (NOLOCK)
                    WHERE   SUSUARIOFILIAL.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA 
                            AND SUSUARIOFILIAL.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
                            AND SUSUARIOFILIAL.CODFILIAL = SHABILITACAOFILIAL.CODFILIAL 
                            AND SUSUARIOFILIAL.CODUSUARIO = PPESSOA.CODUSUARIO
                ) THEN ' SEM PERMISSÃO'
            END)
        ) AS POLO,
        CONCAT(
             SCURSO.NOME, ' (',
             (SELECT TOP 1 CODCURINEP
             FROM    SCURSO A (NOLOCK)
             WHERE   A.CODCOLIGADA=SCURSO.CODCOLIGADA
                     AND A.CODCURINEP IS NOT NULL
                     AND (
                         (STIPOCURSO.NOME LIKE 'POLO %SEMI%' AND (A.COMPLEMENTO=SCURSO.COMPLEMENTO AND A.CODTIPOCURSO=323))
                         OR (STIPOCURSO.NOME LIKE 'POLO %' AND STIPOCURSO.NOME NOT LIKE '%SEMI%' AND (A.COMPLEMENTO=SCURSO.COMPLEMENTO AND A.CODTIPOCURSO=4))
                         OR (STIPOCURSO.NOME NOT LIKE 'POLO %' AND A.CODCURSO=SCURSO.CODCURSO)
                     )),
             ')'
        )                       AS CURSO,
        SPLETIVO.CODPERLET      AS PERIODOLETIVO,
        STATUSPL.DESCRICAO      AS STATUSPERIODO,
        SMATRICPL.PERIODO,
        SHABILITACAOALUNO.IDHABILITACAOFILIAL,
        SHABILITACAOALUNO.IDHABILITACAOFILIALORIGEM,
        STATUSHAB.DESCRICAO     AS STATUSHAB,
        STURNO.NOME AS TURNO,
        (CASE
            WHEN ZMDPOLOS.TIPOENSINO = 'P' THEN 'Presencial'
            WHEN ZMDPOLOS.TIPOENSINO = 'E' AND ISNULL(ZMDPOLOS.POLODIGITAL, 'N') = 'N' THEN 'Flex'
            WHEN ZMDPOLOS.TIPOENSINO = 'E' AND ISNULL(ZMDPOLOS.POLODIGITAL, 'N') = 'S' THEN 'Digital'
            WHEN ZMDPOLOS.TIPOENSINO = 'S' THEN 'Semipresencial'
        END) AS MODALIDADE,
        STIPOINGRESSO.DESCRICAO AS TIPOINGRESSO,
        SHABILITACAOALUNO.DTINGRESSO
FROM    SHABILITACAOALUNO (NOLOCK)
        /* FORMA DE INGRESSO */
        LEFT JOIN STIPOINGRESSO (NOLOCK)
               ON STIPOINGRESSO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
                  AND STIPOINGRESSO.CODTIPOINGRESSO = SHABILITACAOALUNO.CODTIPOINGRESSO
        /* SITUAÇÃO NA MATRIZ APLICADA */
        JOIN SSTATUS STATUSHAB (NOLOCK)
          ON STATUSHAB.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
             AND STATUSHAB.CODSTATUS = SHABILITACAOALUNO.CODSTATUS
        /* ALUNO */
        JOIN SALUNO (NOLOCK)
             JOIN PPESSOA (NOLOCK)
               ON PPESSOA.CODIGO = SALUNO.CODPESSOA
          ON SALUNO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
             AND SALUNO.RA = SHABILITACAOALUNO.RA
        /* CURSO */
        JOIN SHABILITACAOFILIAL (NOLOCK)
             JOIN STURNO (NOLOCK)
               ON STURNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA 
                  AND STURNO.CODTURNO = SHABILITACAOFILIAL.CODTURNO 
             JOIN SCURSO (NOLOCK)
               ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA 
                  AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
          ON SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
             AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL 
        /* NÍVEL DE ENSINO */
        JOIN STIPOCURSO (NOLOCK)
             LEFT JOIN ZMDPOLOS (NOLOCK)
                    ON ZMDPOLOS.CODCOLIGADA = STIPOCURSO.CODCOLIGADA 
                       AND ZMDPOLOS.CODPOLO = STIPOCURSO.CODTIPOCURSO 
              ON STIPOCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA 
                 AND STIPOCURSO.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
        /* MATRÍCULA NO PERÍODO LETIVO */
        LEFT JOIN SMATRICPL (NOLOCK) 
                  JOIN SPLETIVO (NOLOCK)
                    ON SPLETIVO.CODCOLIGADA = SMATRICPL.CODCOLIGADA 
                       AND SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
                  JOIN SSTATUS STATUSPL (NOLOCK)
                    ON STATUSPL.CODCOLIGADA = SMATRICPL.CODCOLIGADA 
                       AND STATUSPL.CODSTATUS = SMATRICPL.CODSTATUS
          ON SMATRICPL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
             AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL 
             AND SMATRICPL.RA = SHABILITACAOALUNO.RA
WHERE   SHABILITACAOALUNO.CODCOLIGADA = :$CODCOLIGADA
        AND SHABILITACAOALUNO.RA = :RA

SELECT  CONCAT(SALUNO.RA, ' - ', PPESSOA.NOME, ' (', PPESSOA.CPF, ')') AS [ALUNO(A)],
	    SPLETIVO.IDPERLET,
        /* STIPOCURSO.CODTIPOCURSO AS COD_POLO, */
        /*(CASE
            WHEN ZMDPOLOS.CODINEP IS NULL THEN STIPOCURSO.NOME
            ELSE CONCAT(STIPOCURSO.NOME, ' (', ZMDPOLOS.CODINEP, ')')
        -- END)                    AS POLO,*/
        CONCAT(
        	STIPOCURSO.CODTIPOCURSO, ' - ',
            STIPOCURSO.NOME, (CASE WHEN ZMDPOLOS.CODINEP IS NOT NULL THEN CONCAT(' (', ZMDPOLOS.CODINEP, ')') END),
            (CASE
                WHEN NOT EXISTS (
                    SELECT  1
                    FROM    SUSUARIOFILIAL (NOLOCK)
                    WHERE   SUSUARIOFILIAL.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA 
                            AND SUSUARIOFILIAL.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
                            AND SUSUARIOFILIAL.CODFILIAL = SHABILITACAOFILIAL.CODFILIAL 
                            AND SUSUARIOFILIAL.CODUSUARIO = PPESSOA.CODUSUARIO
                ) THEN ' SEM PERMISSÃO'
            END)
        ) AS POLO,
        CONCAT(
             SCURSO.NOME, ' (',
             (SELECT TOP 1 CODCURINEP
             FROM    SCURSO A (NOLOCK)
             WHERE   A.CODCOLIGADA=SCURSO.CODCOLIGADA
                     AND A.CODCURINEP IS NOT NULL
                     AND (
                         (STIPOCURSO.NOME LIKE 'POLO %SEMI%' AND (A.COMPLEMENTO=SCURSO.COMPLEMENTO AND A.CODTIPOCURSO=323))
                         OR (STIPOCURSO.NOME LIKE 'POLO %' AND STIPOCURSO.NOME NOT LIKE '%SEMI%' AND (A.COMPLEMENTO=SCURSO.COMPLEMENTO AND A.CODTIPOCURSO=4))
                         OR (STIPOCURSO.NOME NOT LIKE 'POLO %' AND A.CODCURSO=SCURSO.CODCURSO)
                     )),
             ')'
        )                       AS CURSO,
        SPLETIVO.CODPERLET      AS PERIODOLETIVO,
        STATUSPL.DESCRICAO      AS STATUSPERIODO,
        SMATRICPL.PERIODO,
        SHABILITACAOALUNO.IDHABILITACAOFILIAL,
        SHABILITACAOALUNO.IDHABILITACAOFILIALORIGEM,
        STATUSHAB.DESCRICAO     AS STATUSHAB,
        STURNO.NOME AS TURNO,
        (CASE
            WHEN ZMDPOLOS.TIPOENSINO = 'P' THEN 'Presencial'
            WHEN ZMDPOLOS.TIPOENSINO = 'E' AND ISNULL(ZMDPOLOS.POLODIGITAL, 'N') = 'N' THEN 'Flex'
            WHEN ZMDPOLOS.TIPOENSINO = 'E' AND ISNULL(ZMDPOLOS.POLODIGITAL, 'N') = 'S' THEN 'Digital'
            WHEN ZMDPOLOS.TIPOENSINO = 'S' THEN 'Semipresencial'
        END) AS MODALIDADE,
        STIPOINGRESSO.DESCRICAO AS TIPOINGRESSO,
        SHABILITACAOALUNO.DTINGRESSO
FROM    SHABILITACAOALUNO (NOLOCK)
        /* FORMA DE INGRESSO */
        LEFT JOIN STIPOINGRESSO (NOLOCK)
               ON STIPOINGRESSO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
                  AND STIPOINGRESSO.CODTIPOINGRESSO = SHABILITACAOALUNO.CODTIPOINGRESSO
        /* SITUAÇÃO NA MATRIZ APLICADA */
        JOIN SSTATUS STATUSHAB (NOLOCK)
          ON STATUSHAB.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
             AND STATUSHAB.CODSTATUS = SHABILITACAOALUNO.CODSTATUS
        /* ALUNO */
        JOIN SALUNO (NOLOCK)
             JOIN PPESSOA (NOLOCK)
               ON PPESSOA.CODIGO = SALUNO.CODPESSOA
          ON SALUNO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
             AND SALUNO.RA = SHABILITACAOALUNO.RA
        /* CURSO */
        JOIN SHABILITACAOFILIAL (NOLOCK)
             JOIN STURNO (NOLOCK)
               ON STURNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA 
                  AND STURNO.CODTURNO = SHABILITACAOFILIAL.CODTURNO 
             JOIN SCURSO (NOLOCK)
               ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA 
                  AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
          ON SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
             AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL 
        /* NÍVEL DE ENSINO */
        JOIN STIPOCURSO (NOLOCK)
             LEFT JOIN ZMDPOLOS (NOLOCK)
                    ON ZMDPOLOS.CODCOLIGADA = STIPOCURSO.CODCOLIGADA 
                       AND ZMDPOLOS.CODPOLO = STIPOCURSO.CODTIPOCURSO 
              ON STIPOCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA 
                 AND STIPOCURSO.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
        /* MATRÍCULA NO PERÍODO LETIVO */
        LEFT JOIN SMATRICPL (NOLOCK) 
                  JOIN SPLETIVO (NOLOCK)
                    ON SPLETIVO.CODCOLIGADA = SMATRICPL.CODCOLIGADA 
                       AND SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
                  JOIN SSTATUS STATUSPL (NOLOCK)
                    ON STATUSPL.CODCOLIGADA = SMATRICPL.CODCOLIGADA 
                       AND STATUSPL.CODSTATUS = SMATRICPL.CODSTATUS
          ON SMATRICPL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
             AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL 
             AND SMATRICPL.RA = SHABILITACAOALUNO.RA
WHERE   SHABILITACAOALUNO.CODCOLIGADA = :$CODCOLIGADA
        AND SHABILITACAOALUNO.RA = :RA

SELECT DISTINCT
    SALUNO.RA,
    PPESSOA.NOME,
    PPESSOA.CPF
FROM PPESSOA WITH (NOLOCK)
JOIN SALUNO WITH (NOLOCK)
    ON SALUNO.CODPESSOA = PPESSOA.CODIGO
JOIN SHABILITACAOALUNO WITH (NOLOCK)
    ON SHABILITACAOALUNO.CODCOLIGADA = SALUNO.CODCOLIGADA
   AND SHABILITACAOALUNO.RA = SALUNO.RA
JOIN SSTATUS WITH (NOLOCK)
    ON SSTATUS.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
   AND SSTATUS.CODSTATUS = SHABILITACAOALUNO.CODSTATUS
WHERE PPESSOA.CPF IN (
    '62335199340',
    '93113315387',
    '05895155359',
    '06999742324',
    '06846143327',
    '62403847399',
    '08251343313',
    '03428429354',
    '62541164300',
    '63164714327',
    '08645931397',
    '07457803343',
    '08117472392',
    '82237077304',
    '07513726337',
    '04930790336',
    '04434861310',
    '83324119391',
    '01031634339',
    '60844478300',
    '04685174305',
    '07830698392',
    '80368263304',
    '95119540325',
    '00441494331',
    '67899986320',
    '05368958307',
    '02824726300',
    '09020374397',
    '03198507308',
    '00740570307',
    '15644946754',
    '07039176335',
    '87256932391',
    '04655175362',
    '00372219306',
    '00702570354',
    '62548346340',
    '03695060492',
    '62453099302',
    '87787539372',
    '03832846352',
    '05240967326',
    '97910341334',
    '01796532371',
    '89557662387',
    '08371739303',
    '08374726369'
)
AND SALUNO.CODCOLIGADA = 1
AND SSTATUS.DESCRICAO IN ('ATIVO', 'GRADUADO(A)')

SELECT DISTINCT 
        SMATRICPL.CODCOLIGADA,
        SMATRICPL.RA,
        SMATRICPL.IDHABILITACAOFILIAL,                                         
        SPLETIVO.CODPERLET,
        SCURSO.CODCURSO,
        SCURSO.NOME       NOMECURSO,
        STURNO.NOME       NOMETURNO,  
        PPESSOA.NOME      NOMEALUNO,
        PPESSOA.CPF,
        SSTATUS.DESCRICAO NOMESTATUS,
        STIPOMATRICULA.DESCRICAO NOMETIPOMAT        
FROM   SHABILITACAOALUNO (NOLOCK)
       JOIN SHABILITACAOFILIAL (NOLOCK)
         ON SHABILITACAOALUNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
            AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
       JOIN SPLETIVO (NOLOCK)
         ON SPLETIVO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
            AND SPLETIVO.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
       JOIN SMATRICPL (NOLOCK)
         ON SMATRICPL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
            AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
            AND SMATRICPL.RA = SHABILITACAOALUNO.RA
            AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
       JOIN SCURSO (NOLOCK)
         ON SHABILITACAOFILIAL.CODCOLIGADA = SCURSO.CODCOLIGADA
            AND SHABILITACAOFILIAL.CODCURSO = SCURSO.CODCURSO
       JOIN SHABILITACAO (NOLOCK)
         ON SHABILITACAO.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
            AND SCURSO.CODCOLIGADA = SHABILITACAO.CODCOLIGADA
            AND SCURSO.CODCURSO = SHABILITACAO.CODCURSO
       JOIN SGRADE (NOLOCK)
         ON SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
            AND SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
            AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
            AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
       JOIN STURNO (NOLOCK)
         ON SHABILITACAOFILIAL.CODCOLIGADA = STURNO.CODCOLIGADA
            AND SHABILITACAOFILIAL.CODTURNO = STURNO.CODTURNO
       JOIN SSTATUS (NOLOCK)
         ON SSTATUS.CODCOLIGADA = SMATRICPL.CODCOLIGADA
            AND SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS
       JOIN SALUNO (NOLOCK)
         ON SALUNO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
            AND SALUNO.RA = SMATRICPL.RA
       JOIN PPESSOA (NOLOCK)
         ON PPESSOA.CODIGO = SALUNO.CODPESSOA
       LEFT JOIN SSTATUS SSTATUSRES (NOLOCK)
         ON ( SMATRICPL.CODCOLIGADA = SSTATUSRES.CODCOLIGADA
            AND SMATRICPL.CODSTATUSRES = SSTATUSRES.CODSTATUS ) 
       LEFT JOIN SMATRICPLITEMCNT (NOLOCK)
         ON ( SMATRICPL.CODCOLIGADA = SMATRICPLITEMCNT.CODCOLIGADA 
            AND SMATRICPL.IDPERLET = SMATRICPLITEMCNT.IDPERLET
            AND SMATRICPL.IDHABILITACAOFILIAL = SMATRICPLITEMCNT.IDHABILITACAOFILIAL
            AND SMATRICPL.RA = SMATRICPLITEMCNT.RA ) 
       LEFT JOIN STIPOMATRICULA (NOLOCK)
              ON SMATRICPL.CODCOLIGADA = STIPOMATRICULA.CODCOLIGADA
                 AND SMATRICPL.CODTIPOMAT = STIPOMATRICULA.CODTIPOMAT 
WHERE SMATRICPL.CODCOLIGADA = 1
                AND SMATRICPL.CODFILIAL = 1
                AND SHABILITACAOFILIAL.CODTIPOCURSO IN (1,195,196,281,285,345,357,424) 
                AND SPLETIVO.CODPERLET = '2026.1'
                AND (SSTATUS.DESCRICAO LIKE 'PENDENTE PAGAMENTO' 
                     OR SSTATUS.DESCRICAO LIKE 'PENDENTE PAGAMENTO/ADITAMENTO'
                     OR SSTATUS.DESCRICAO LIKE 'PENDENTE ADITAMENTO'
                     OR SSTATUS.DESCRICAO LIKE 'MATRICULADO (PERIODO LETIVO)'
                     OR SSTATUS.DESCRICAO LIKE  'TRANCADO')
                     

                     
SELECT
	CASE /*RETORNA SUGESTÃO DE E-MAIL INSTITUCIONAL, CASO A PESSOA POSSUA UM NOME SOCIAL O NOME SOCIAL É UTILIZADO NA COMPOSIÇÃO DO E-MAIL*/
		WHEN PPESSOA.NOMESOCIAL IS NOT NULL THEN SUBSTRING(PPESSOA.NOMESOCIAL, 1, CHARINDEX(' ', PPESSOA.NOMESOCIAL + ' ') - 1) + '.' + SALUNO.RA + '@discentes.uninta.edu.br'
		ELSE SUBSTRING(PPESSOA.NOME, 1, CHARINDEX(' ', PPESSOA.NOME + ' ') - 1) + '.' + SALUNO.RA + '@discentes.uninta.edu.br'		
	END AS [Nome de usuário],
	SUBSTRING(PPESSOA.NOME, 1, CHARINDEX(' ', PPESSOA.NOME + ' ') - 1) AS [Nome],
	RIGHT(LTRIM(RTRIM(PPESSOA.NOME)),
      CHARINDEX(' ', REVERSE(LTRIM(RTRIM(PPESSOA.NOME))) + ' ') - 1) AS [Sobrenome],
	COALESCE(
    NULLIF(SUBSTRING(LTRIM(RTRIM(PPESSOA.NOMESOCIAL)), 1,
      CHARINDEX(' ', LTRIM(RTRIM(PPESSOA.NOMESOCIAL)) + ' ') - 1), ''),
    SUBSTRING(LTRIM(RTRIM(PPESSOA.NOME)), 1,
      CHARINDEX(' ', LTRIM(RTRIM(PPESSOA.NOME)) + ' ') - 1)) + ' ' + RIGHT(LTRIM(RTRIM(PPESSOA.NOME)),
      CHARINDEX(' ', REVERSE(LTRIM(RTRIM(PPESSOA.NOME))) + ' ') - 1) 
      AS [Nome de exibição],
	'DISCENTE' AS Cargo,
	'UNINTA' AS Departamento,
	'' AS [Número comercial],
	'' AS [Telefone comercial],
	'' AS [Celular],
	'' AS [Fax],
	'' AS [Endereço de email alternativo],
	'' AS [Endereço],
	'' AS [Cidade],
	'' AS [Estado ou província],
	'' AS [CEP],
	'' AS [País ou região]
	/*PPESSOA.NOMESOCIAL,
	SALUNO.RA,
	PPESSOA.NOME AS [NOME COMPLETO],*/
FROM SALUNO WITH (NOLOCK)
	JOIN PPESSOA WITH (NOLOCK)
		ON PPESSOA.CODIGO = SALUNO.CODPESSOA
	JOIN SHABILITACAOALUNO WITH (NOLOCK)
		ON SHABILITACAOALUNO.CODCOLIGADA = SALUNO.CODCOLIGADA
			AND SHABILITACAOALUNO.RA = SALUNO.RA
	JOIN SHABILITACAOFILIAL WITH (NOLOCK)
		ON SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
			AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL 
	JOIN SMATRICPL WITH (NOLOCK)
		ON SMATRICPL.CODCOLIGADA = SALUNO.CODCOLIGADA
	 	    AND SMATRICPL.RA = SALUNO.RA
	JOIN SPLETIVO WITH (NOLOCK)
		ON SPLETIVO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
			AND SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
	JOIN SCURSO WITH (NOLOCK)
		ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
			AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	JOIN SSTATUS SSTATUSHABILITACAO WITH (NOLOCK)
		ON SSTATUSHABILITACAO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
			AND SSTATUSHABILITACAO.CODSTATUS = SHABILITACAOALUNO.CODSTATUS
	JOIN SSTATUS SSTATUSMATRICPL WITH (NOLOCK)
		ON SSTATUSMATRICPL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
			AND SSTATUSMATRICPL.CODSTATUS = SMATRICPL.CODSTATUS
WHERE
	SHABILITACAOFILIAL.CODCOLIGADA = 1
	AND SPLETIVO.CODTIPOCURSO NOT IN (2, 5, 195, 196, 285, 281, 424, 345, 357)
	AND SSTATUSHABILITACAO.DESCRICAO = 'ATIVO'
	AND SPLETIVO.CODPERLET = :CODPERLET
	AND SSTATUSMATRICPL.DESCRICAO IN ('MATRICULADO (PERIODO LETIVO)', 'PENDENTE PAGAMENTO', 'PENDENTE ADITAMENTO', 'PENDENTE PAGAMENTO/ADITAMENTO')


-- CONSULTA PARA BUSCAR CPF ATRAVÉS DO USUÁRIO
SELECT 
    PPESSOA.CODUSUARIO AS USUARIO,
    PPESSOA.NOME,
    PPESSOA.CPF,
    SALUNO.RA,
    PFUNC.CODSITUACAO AS STATUS_COLABORADOR
FROM PPESSOA WITH (NOLOCK)
LEFT JOIN SALUNO WITH (NOLOCK)
    ON SALUNO.CODPESSOA = PPESSOA.CODIGO
LEFT JOIN (
    SELECT 
        CODPESSOA,
        CODSITUACAO,
        ROW_NUMBER() OVER (PARTITION BY CODPESSOA ORDER BY CASE WHEN CODSITUACAO = 'A' THEN 0 ELSE 1 END) AS RN
    FROM PFUNC WITH (NOLOCK)
) PFUNC
    ON PFUNC.CODPESSOA = PPESSOA.CODIGO 
    AND PFUNC.RN = 1
WHERE PPESSOA.CODUSUARIO = '2022118497'
-- OU use: WHERE PPESSOA.CODUSUARIO LIKE '%parte_do_usuario%'


SELECT 
    PPESSOA.CODUSUARIO AS USUARIO,
    PPESSOA.NOME,
    PPESSOA.CPF,
    SALUNO.RA
FROM PPESSOA WITH (NOLOCK)
LEFT JOIN SALUNO WITH (NOLOCK)
    ON SALUNO.CODPESSOA = PPESSOA.CODIGO
WHERE PPESSOA.CODUSUARIO = '1-07337'


SELECT 
    PPESSOA.CODUSUARIO AS USUARIO,
    PPESSOA.NOME,
    PPESSOA.CPF,
    SALUNO.RA,
    CASE 
        WHEN PFUNC.CODPESSOA IS NOT NULL THEN 'SIM' 
        ELSE 'NÃO' 
    END AS COLABORADOR,
    PFUNC.CODSITUACAO AS STATUS_COLABORADOR,
    CASE 
        WHEN PFUNC.CODSITUACAO = 'A' THEN 'ATIVO' 
        WHEN PFUNC.CODSITUACAO IS NOT NULL THEN 'INATIVO'
        ELSE NULL
    END AS DESC_STATUS
FROM PPESSOA WITH (NOLOCK)
LEFT JOIN SALUNO WITH (NOLOCK)
    ON SALUNO.CODPESSOA = PPESSOA.CODIGO
LEFT JOIN PFUNC WITH (NOLOCK)
    ON PFUNC.CODPESSOA = PPESSOA.CODIGO
WHERE PPESSOA.CODUSUARIO = '1-03667'


/* ========================================================================== */
/* CONSULTA DE TURMAS/DISCIPLINAS DO ALUNO NO PERÍODO LETIVO MAIS ATUAL */
/* ========================================================================== */
SELECT  CONCAT(SALUNO.RA, ' - ', PPESSOA.NOME, ' (', PPESSOA.CPF, ')') AS [ALUNO(A)],
        SPLETIVO.IDPERLET,
        SPLETIVO.CODPERLET      AS PERIODOLETIVO,
        /* POLO */
        CONCAT(
            STIPOCURSO.CODTIPOCURSO, ' - ',
            STIPOCURSO.NOME, (CASE WHEN ZMDPOLOS.CODINEP IS NOT NULL THEN CONCAT(' (', ZMDPOLOS.CODINEP, ')') END),
            (CASE
                WHEN NOT EXISTS (
                    SELECT  1
                    FROM    SUSUARIOFILIAL (NOLOCK)
                    WHERE   SUSUARIOFILIAL.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA 
                            AND SUSUARIOFILIAL.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
                            AND SUSUARIOFILIAL.CODFILIAL = SHABILITACAOFILIAL.CODFILIAL 
                            AND SUSUARIOFILIAL.CODUSUARIO = PPESSOA.CODUSUARIO
                ) THEN ' SEM PERMISSÃO'
            END)
        ) AS POLO,
        /* CURSO */
        CONCAT(
             SCURSO.NOME, ' (',
             (SELECT TOP 1 CODCURINEP
             FROM    SCURSO A (NOLOCK)
             WHERE   A.CODCOLIGADA=SCURSO.CODCOLIGADA
                     AND A.CODCURINEP IS NOT NULL
                     AND (
                         (STIPOCURSO.NOME LIKE 'POLO %SEMI%' AND (A.COMPLEMENTO=SCURSO.COMPLEMENTO AND A.CODTIPOCURSO=323))
                         OR (STIPOCURSO.NOME LIKE 'POLO %' AND STIPOCURSO.NOME NOT LIKE '%SEMI%' AND (A.COMPLEMENTO=SCURSO.COMPLEMENTO AND A.CODTIPOCURSO=4))
                         OR (STIPOCURSO.NOME NOT LIKE 'POLO %' AND A.CODCURSO=SCURSO.CODCURSO)
                     )),
             ')'
        )                       AS CURSO,
        STATUSPL.DESCRICAO      AS STATUSPERIODO,
        SMATRICPL.PERIODO,
        SHABILITACAOALUNO.IDHABILITACAOFILIAL,
        SHABILITACAOALUNO.IDHABILITACAOFILIALORIGEM,
        STATUSHAB.DESCRICAO     AS STATUSHAB,
        STURNO.NOME AS TURNO,
        (CASE
            WHEN ZMDPOLOS.TIPOENSINO = 'P' THEN 'Presencial'
            WHEN ZMDPOLOS.TIPOENSINO = 'E' AND ISNULL(ZMDPOLOS.POLODIGITAL, 'N') = 'N' THEN 'Flex'
            WHEN ZMDPOLOS.TIPOENSINO = 'E' AND ISNULL(ZMDPOLOS.POLODIGITAL, 'N') = 'S' THEN 'Digital'
            WHEN ZMDPOLOS.TIPOENSINO = 'S' THEN 'Semipresencial'
        END) AS MODALIDADE,
        STIPOINGRESSO.DESCRICAO AS TIPOINGRESSO,
        SHABILITACAOALUNO.DTINGRESSO,
        /* INFORMAÇÕES DA DISCIPLINA */
        SDISCIPLINA.CODDISC,
        SDISCIPLINA.NOME        AS DISCIPLINA,
        SMATRICDISC.CODTURMADISC,
        STURMADISC.CODTURMA,
        STURMADISC.NUMTURMA,
        SMATRICDISC.CODSTATUSDISC,
        STATUSDISC.DESCRICAO    AS STATUSDISCIPLINA,
        SMATRICDISC.NOTA,
        SMATRICDISC.NOTAFINAL,
        SMATRICDISC.FALTA,
        SMATRICDISC.MEDIAAPROVACAO,
        SMATRICDISC.PERCFREQAPROV
FROM    SHABILITACAOALUNO (NOLOCK)
        /* FORMA DE INGRESSO */
        LEFT JOIN STIPOINGRESSO (NOLOCK)
               ON STIPOINGRESSO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
                  AND STIPOINGRESSO.CODTIPOINGRESSO = SHABILITACAOALUNO.CODTIPOINGRESSO
        /* SITUAÇÃO NA MATRIZ APLICADA */
        JOIN SSTATUS STATUSHAB (NOLOCK)
          ON STATUSHAB.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
             AND STATUSHAB.CODSTATUS = SHABILITACAOALUNO.CODSTATUS
        /* ALUNO */
        JOIN SALUNO (NOLOCK)
             JOIN PPESSOA (NOLOCK)
               ON PPESSOA.CODIGO = SALUNO.CODPESSOA
          ON SALUNO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
             AND SALUNO.RA = SHABILITACAOALUNO.RA
        /* CURSO */
        JOIN SHABILITACAOFILIAL (NOLOCK)
             JOIN STURNO (NOLOCK)
               ON STURNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA 
                  AND STURNO.CODTURNO = SHABILITACAOFILIAL.CODTURNO 
             JOIN SCURSO (NOLOCK)
               ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA 
                  AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
          ON SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
             AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL 
        /* NÍVEL DE ENSINO */
        JOIN STIPOCURSO (NOLOCK)
             LEFT JOIN ZMDPOLOS (NOLOCK)
                    ON ZMDPOLOS.CODCOLIGADA = STIPOCURSO.CODCOLIGADA 
                       AND ZMDPOLOS.CODPOLO = STIPOCURSO.CODTIPOCURSO 
              ON STIPOCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA 
                 AND STIPOCURSO.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
        /* MATRÍCULA NO PERÍODO LETIVO MAIS ATUAL */
        JOIN SMATRICPL (NOLOCK) 
             JOIN SPLETIVO (NOLOCK)
               ON SPLETIVO.CODCOLIGADA = SMATRICPL.CODCOLIGADA 
                  AND SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
             JOIN SSTATUS STATUSPL (NOLOCK)
               ON STATUSPL.CODCOLIGADA = SMATRICPL.CODCOLIGADA 
                  AND STATUSPL.CODSTATUS = SMATRICPL.CODSTATUS
          ON SMATRICPL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
             AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL 
             AND SMATRICPL.RA = SHABILITACAOALUNO.RA
             /* FILTRO PARA PEGAR O PERÍODO LETIVO MAIS ATUAL */
             AND SMATRICPL.IDPERLET = (
                 SELECT  TOP 1 IDPERLET
                 FROM    SMATRICPL MP (NOLOCK)
                 WHERE   MP.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
                         AND MP.RA = SHABILITACAOALUNO.RA
                         AND MP.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
                 ORDER BY MP.IDPERLET DESC
             )
        /* MATRÍCULA EM DISCIPLINAS */
        JOIN SMATRICDISC (NOLOCK)
             JOIN STURMADISC (NOLOCK)
                  JOIN SDISCIPLINA (NOLOCK)
                    ON SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
                       AND SDISCIPLINA.CODDISC = STURMADISC.CODDISC
               ON STURMADISC.CODCOLIGADA = SMATRICDISC.CODCOLIGADA
                  AND STURMADISC.IDTURMADISC = SMATRICDISC.IDTURMADISC
             JOIN SSTATUS STATUSDISC (NOLOCK)
               ON STATUSDISC.CODCOLIGADA = SMATRICDISC.CODCOLIGADA
                  AND STATUSDISC.CODSTATUS = SMATRICDISC.CODSTATUSDISC
          ON SMATRICDISC.CODCOLIGADA = SMATRICPL.CODCOLIGADA
             AND SMATRICDISC.IDPERLET = SMATRICPL.IDPERLET
             AND SMATRICDISC.RA = SMATRICPL.RA
             AND SMATRICDISC.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
WHERE   SHABILITACAOALUNO.CODCOLIGADA = :$CODCOLIGADA
        AND SHABILITACAOALUNO.RA = :RA
ORDER BY SDISCIPLINA.NOME

